// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../error.dart';
import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'package:freezed_annotation/freezed_annotation.dart' hide protected;
part 'phase.freezed.dart';

/// 章节条目
@freezed
sealed class ChapterItem with _$ChapterItem {
  const factory ChapterItem({
    required String title,
    String? url,
  }) = _ChapterItem;
}

/// 内容页数据
@freezed
sealed class ContentData with _$ContentData {
  const factory ContentData({
    required String content,
    required List<String> media,
  }) = _ContentData;
}

/// 响应内容类型
enum ContentType {
  html,
  json,
  xml,
}

/// 详情页数据
@freezed
sealed class DetailData with _$DetailData {
  const factory DetailData({
    required Map<String, String> fields,
  }) = _DetailData;
}

/// 发现页数据
@freezed
sealed class ExploreData with _$ExploreData {
  const factory ExploreData({
    required List<String> items,
  }) = _ExploreData;
}

/// 生命周期阶段
enum LifecyclePhase {
  explore,
  search,
  detail,
  toc,
  content,
}

/// 阶段执行上下文
@freezed
sealed class PhaseContext with _$PhaseContext {
  const factory PhaseContext({
    String? url,
    String? keyword,
    int? page,
    Map<String, String>? vars,
  }) = _PhaseContext;
}

@freezed
sealed class PhaseData with _$PhaseData {
  const PhaseData._();

  const factory PhaseData.explore(
    ExploreData field0,
  ) = PhaseData_Explore;
  const factory PhaseData.search(
    SearchData field0,
  ) = PhaseData_Search;
  const factory PhaseData.detail(
    DetailData field0,
  ) = PhaseData_Detail;
  const factory PhaseData.toc(
    TocData field0,
  ) = PhaseData_Toc;
  const factory PhaseData.content(
    ContentData field0,
  ) = PhaseData_Content;
}

/// 阶段执行返回结果
@freezed
sealed class PhaseResult with _$PhaseResult {
  const factory PhaseResult({
    required bool success,
    String? finalUrl,
    required ContentType contentType,
    String? rawBody,
    PhaseData? data,
    CrawlerError? error,
  }) = _PhaseResult;
}

/// 搜索页数据
@freezed
sealed class SearchData with _$SearchData {
  const factory SearchData({
    required List<SearchItem> items,
  }) = _SearchData;
}

/// 搜索结果条目
@freezed
sealed class SearchItem with _$SearchItem {
  const factory SearchItem({
    required String title,
    required String url,
    String? cover,
    String? author,
  }) = _SearchItem;
}

/// 目录页数据
@freezed
sealed class TocData with _$TocData {
  const factory TocData({
    required List<ChapterItem> chapters,
  }) = _TocData;
}
