// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

#![allow(
    non_camel_case_types,
    unused,
    non_snake_case,
    clippy::needless_return,
    clippy::redundant_closure_call,
    clippy::redundant_closure,
    clippy::useless_conversion,
    clippy::unit_arg,
    clippy::unused_unit,
    clippy::double_parens,
    clippy::let_and_return,
    clippy::too_many_arguments,
    clippy::match_single_binding,
    clippy::clone_on_copy,
    clippy::let_unit_value,
    clippy::deref_addrof,
    clippy::explicit_auto_deref,
    clippy::borrow_deref_ref,
    clippy::needless_borrow
)]

// Section: imports

use flutter_rust_bridge::{
    Handler, IntoIntoDart,
    for_generated::{
        Lifetimeable, Lockable,
        byteorder::{NativeEndian, ReadBytesExt, WriteBytesExt},
        transform_result_dco,
    },
};

// Section: boilerplate

flutter_rust_bridge::frb_generated_boilerplate!(
    default_stream_sink_codec = SseCodec,
    default_rust_opaque = RustOpaqueMoi,
    default_rust_auto_opaque = RustAutoOpaqueMoi,
);
pub(crate) const FLUTTER_RUST_BRIDGE_CODEGEN_VERSION: &str = "2.11.1";
pub(crate) const FLUTTER_RUST_BRIDGE_CODEGEN_CONTENT_HASH: i32 = -550374770;

// Section: executor

flutter_rust_bridge::frb_generated_default_handler!();

// Section: wire_funcs

fn wire__crate__ffi__execute_rule_impl(
    port_: flutter_rust_bridge::for_generated::MessagePort,
    ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len_: i32,
    data_len_: i32,
) {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_async::<flutter_rust_bridge::for_generated::SseCodec, _, _, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "execute_rule",
            port: Some(port_),
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Normal,
        },
        move || {
            let message = unsafe {
                flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(
                    ptr_,
                    rust_vec_len_,
                    data_len_,
                )
            };
            let mut deserializer =
                flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            let api_envelope_json = <String>::sse_decode(&mut deserializer);
            let api_context =
                <Option<crate::ffi::FfiExecuteContext>>::sse_decode(&mut deserializer);
            deserializer.end();
            move |context| async move {
                transform_result_sse::<_, ()>(
                    (move || async move {
                        let output_ok = Result::<_, ()>::Ok(
                            crate::ffi::execute_rule(api_envelope_json, api_context).await,
                        )?;
                        Ok(output_ok)
                    })()
                    .await,
                )
            }
        },
    )
}
fn wire__crate__ffi__ffi_execute_context_default_impl(
    port_: flutter_rust_bridge::for_generated::MessagePort,
    ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len_: i32,
    data_len_: i32,
) {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_normal::<flutter_rust_bridge::for_generated::SseCodec, _, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "ffi_execute_context_default",
            port: Some(port_),
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Normal,
        },
        move || {
            let message = unsafe {
                flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(
                    ptr_,
                    rust_vec_len_,
                    data_len_,
                )
            };
            let mut deserializer =
                flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            deserializer.end();
            move |context| {
                transform_result_sse::<_, ()>((move || {
                    let output_ok = Result::<_, ()>::Ok(crate::ffi::FfiExecuteContext::default())?;
                    Ok(output_ok)
                })())
            }
        },
    )
}
fn wire__crate__ffi__ping_impl(
    ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len_: i32,
    data_len_: i32,
) -> flutter_rust_bridge::for_generated::WireSyncRust2DartSse {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_sync::<flutter_rust_bridge::for_generated::SseCodec, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "ping",
            port: None,
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Sync,
        },
        move || {
            let message = unsafe {
                flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(
                    ptr_,
                    rust_vec_len_,
                    data_len_,
                )
            };
            let mut deserializer =
                flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            deserializer.end();
            transform_result_sse::<_, ()>((move || {
                let output_ok = Result::<_, ()>::Ok(crate::ffi::ping())?;
                Ok(output_ok)
            })())
        },
    )
}
fn wire__crate__ffi__validate_rule_impl(
    ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len_: i32,
    data_len_: i32,
) -> flutter_rust_bridge::for_generated::WireSyncRust2DartSse {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_sync::<flutter_rust_bridge::for_generated::SseCodec, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "validate_rule",
            port: None,
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Sync,
        },
        move || {
            let message = unsafe {
                flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(
                    ptr_,
                    rust_vec_len_,
                    data_len_,
                )
            };
            let mut deserializer =
                flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            let api_envelope_json = <String>::sse_decode(&mut deserializer);
            deserializer.end();
            transform_result_sse::<_, ()>((move || {
                let output_ok = Result::<_, ()>::Ok(crate::ffi::validate_rule(api_envelope_json))?;
                Ok(output_ok)
            })())
        },
    )
}

// Section: dart2rust

impl SseDecode for std::collections::HashMap<String, String> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut inner = <Vec<(String, String)>>::sse_decode(deserializer);
        return inner.into_iter().collect();
    }
}

impl SseDecode for String {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut inner = <Vec<u8>>::sse_decode(deserializer);
        return String::from_utf8(inner).unwrap();
    }
}

impl SseDecode for bool {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        deserializer.cursor.read_u8().unwrap() != 0
    }
}

impl SseDecode for crate::rules_ir::normalized_model::ChapterItem {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut var_title = <String>::sse_decode(deserializer);
        let mut var_url = <Option<String>>::sse_decode(deserializer);
        return crate::rules_ir::normalized_model::ChapterItem {
            title: var_title,
            url: var_url,
        };
    }
}

impl SseDecode for crate::rules_ir::normalized_model::ContentModel {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut var_contentTextHtml = <Option<String>>::sse_decode(deserializer);
        let mut var_contentTextPlain = <Option<String>>::sse_decode(deserializer);
        let mut var_mediaAssets =
            <Vec<crate::rules_ir::normalized_model::MediaAsset>>::sse_decode(deserializer);
        return crate::rules_ir::normalized_model::ContentModel {
            content_text_html: var_contentTextHtml,
            content_text_plain: var_contentTextPlain,
            media_assets: var_mediaAssets,
        };
    }
}

impl SseDecode for crate::rules_ir::normalized_model::DetailModel {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut var_title = <String>::sse_decode(deserializer);
        let mut var_cover = <Option<String>>::sse_decode(deserializer);
        let mut var_author = <Option<String>>::sse_decode(deserializer);
        let mut var_description = <Option<String>>::sse_decode(deserializer);
        let mut var_tags = <Vec<String>>::sse_decode(deserializer);
        return crate::rules_ir::normalized_model::DetailModel {
            title: var_title,
            cover: var_cover,
            author: var_author,
            description: var_description,
            tags: var_tags,
        };
    }
}

impl SseDecode for crate::ffi::FfiDiagnostic {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut var_code = <String>::sse_decode(deserializer);
        let mut var_path = <String>::sse_decode(deserializer);
        let mut var_message = <String>::sse_decode(deserializer);
        let mut var_nodeId = <Option<String>>::sse_decode(deserializer);
        return crate::ffi::FfiDiagnostic {
            code: var_code,
            path: var_path,
            message: var_message,
            node_id: var_nodeId,
        };
    }
}

impl SseDecode for crate::ffi::FfiExecuteContext {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut var_runId = <Option<String>>::sse_decode(deserializer);
        let mut var_traceId = <Option<String>>::sse_decode(deserializer);
        let mut var_channelCapacity = <Option<i32>>::sse_decode(deserializer);
        let mut var_ruleId = <Option<String>>::sse_decode(deserializer);
        let mut var_ruleKvJson = <Option<String>>::sse_decode(deserializer);
        let mut var_cookieJarJson = <Option<String>>::sse_decode(deserializer);
        return crate::ffi::FfiExecuteContext {
            run_id: var_runId,
            trace_id: var_traceId,
            channel_capacity: var_channelCapacity,
            rule_id: var_ruleId,
            rule_kv_json: var_ruleKvJson,
            cookie_jar_json: var_cookieJarJson,
        };
    }
}

impl SseDecode for crate::ffi::FfiExecuteError {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut var_code = <String>::sse_decode(deserializer);
        let mut var_message = <String>::sse_decode(deserializer);
        let mut var_diagnostics = <Vec<crate::ffi::FfiDiagnostic>>::sse_decode(deserializer);
        return crate::ffi::FfiExecuteError {
            code: var_code,
            message: var_message,
            diagnostics: var_diagnostics,
        };
    }
}

impl SseDecode for crate::ffi::FfiExecuteResponse {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut var_runId = <Option<String>>::sse_decode(deserializer);
        let mut var_initialResultJson = <Option<String>>::sse_decode(deserializer);
        let mut var_error = <Option<crate::ffi::FfiExecuteError>>::sse_decode(deserializer);
        let mut var_ruleKvJson = <Option<String>>::sse_decode(deserializer);
        let mut var_cookieJarJson = <Option<String>>::sse_decode(deserializer);
        return crate::ffi::FfiExecuteResponse {
            run_id: var_runId,
            initial_result_json: var_initialResultJson,
            error: var_error,
            rule_kv_json: var_ruleKvJson,
            cookie_jar_json: var_cookieJarJson,
        };
    }
}

impl SseDecode for crate::ffi::FfiValidationResult {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut var_valid = <bool>::sse_decode(deserializer);
        let mut var_diagnostics = <Vec<crate::ffi::FfiDiagnostic>>::sse_decode(deserializer);
        return crate::ffi::FfiValidationResult {
            valid: var_valid,
            diagnostics: var_diagnostics,
        };
    }
}

impl SseDecode for i32 {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        deserializer.cursor.read_i32::<NativeEndian>().unwrap()
    }
}

impl SseDecode for Vec<String> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut len_ = <i32>::sse_decode(deserializer);
        let mut ans_ = vec![];
        for idx_ in 0..len_ {
            ans_.push(<String>::sse_decode(deserializer));
        }
        return ans_;
    }
}

impl SseDecode for Vec<crate::rules_ir::normalized_model::ChapterItem> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut len_ = <i32>::sse_decode(deserializer);
        let mut ans_ = vec![];
        for idx_ in 0..len_ {
            ans_.push(<crate::rules_ir::normalized_model::ChapterItem>::sse_decode(deserializer));
        }
        return ans_;
    }
}

impl SseDecode for Vec<crate::ffi::FfiDiagnostic> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut len_ = <i32>::sse_decode(deserializer);
        let mut ans_ = vec![];
        for idx_ in 0..len_ {
            ans_.push(<crate::ffi::FfiDiagnostic>::sse_decode(deserializer));
        }
        return ans_;
    }
}

impl SseDecode for Vec<crate::rules_ir::normalized_model::MediaAsset> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut len_ = <i32>::sse_decode(deserializer);
        let mut ans_ = vec![];
        for idx_ in 0..len_ {
            ans_.push(<crate::rules_ir::normalized_model::MediaAsset>::sse_decode(
                deserializer,
            ));
        }
        return ans_;
    }
}

impl SseDecode for Vec<u8> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut len_ = <i32>::sse_decode(deserializer);
        let mut ans_ = vec![];
        for idx_ in 0..len_ {
            ans_.push(<u8>::sse_decode(deserializer));
        }
        return ans_;
    }
}

impl SseDecode for Vec<(String, String)> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut len_ = <i32>::sse_decode(deserializer);
        let mut ans_ = vec![];
        for idx_ in 0..len_ {
            ans_.push(<(String, String)>::sse_decode(deserializer));
        }
        return ans_;
    }
}

impl SseDecode for Vec<crate::rules_ir::normalized_model::SearchItem> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut len_ = <i32>::sse_decode(deserializer);
        let mut ans_ = vec![];
        for idx_ in 0..len_ {
            ans_.push(<crate::rules_ir::normalized_model::SearchItem>::sse_decode(
                deserializer,
            ));
        }
        return ans_;
    }
}

impl SseDecode for crate::rules_ir::normalized_model::MediaAsset {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut var_mediaType =
            <crate::rules_ir::normalized_model::MediaType>::sse_decode(deserializer);
        let mut var_url = <String>::sse_decode(deserializer);
        let mut var_title = <Option<String>>::sse_decode(deserializer);
        let mut var_cover = <Option<String>>::sse_decode(deserializer);
        return crate::rules_ir::normalized_model::MediaAsset {
            media_type: var_mediaType,
            url: var_url,
            title: var_title,
            cover: var_cover,
        };
    }
}

impl SseDecode for crate::rules_ir::normalized_model::MediaExtension {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut var_video =
            <Option<crate::rules_ir::normalized_model::MediaSpec>>::sse_decode(deserializer);
        let mut var_music =
            <Option<crate::rules_ir::normalized_model::MediaSpec>>::sse_decode(deserializer);
        let mut var_novel =
            <Option<crate::rules_ir::normalized_model::MediaSpec>>::sse_decode(deserializer);
        let mut var_comic =
            <Option<crate::rules_ir::normalized_model::MediaSpec>>::sse_decode(deserializer);
        let mut var_image =
            <Option<crate::rules_ir::normalized_model::MediaSpec>>::sse_decode(deserializer);
        return crate::rules_ir::normalized_model::MediaExtension {
            video: var_video,
            music: var_music,
            novel: var_novel,
            comic: var_comic,
            image: var_image,
        };
    }
}

impl SseDecode for crate::rules_ir::normalized_model::MediaSpec {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut var_extra = <std::collections::HashMap<String, String>>::sse_decode(deserializer);
        return crate::rules_ir::normalized_model::MediaSpec { extra: var_extra };
    }
}

impl SseDecode for crate::rules_ir::normalized_model::MediaType {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut inner = <i32>::sse_decode(deserializer);
        return match inner {
            0 => crate::rules_ir::normalized_model::MediaType::Video,
            1 => crate::rules_ir::normalized_model::MediaType::Music,
            2 => crate::rules_ir::normalized_model::MediaType::Novel,
            3 => crate::rules_ir::normalized_model::MediaType::Comic,
            4 => crate::rules_ir::normalized_model::MediaType::Image,
            _ => unreachable!("Invalid variant for MediaType: {}", inner),
        };
    }
}

impl SseDecode for crate::rules_ir::normalized_model::NormalizedModel {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut var_search =
            <Option<crate::rules_ir::normalized_model::SearchModel>>::sse_decode(deserializer);
        let mut var_detail =
            <Option<crate::rules_ir::normalized_model::DetailModel>>::sse_decode(deserializer);
        let mut var_toc =
            <Option<crate::rules_ir::normalized_model::TocModel>>::sse_decode(deserializer);
        let mut var_content =
            <Option<crate::rules_ir::normalized_model::ContentModel>>::sse_decode(deserializer);
        let mut var_media =
            <Option<crate::rules_ir::normalized_model::MediaExtension>>::sse_decode(deserializer);
        return crate::rules_ir::normalized_model::NormalizedModel {
            search: var_search,
            detail: var_detail,
            toc: var_toc,
            content: var_content,
            media: var_media,
        };
    }
}

impl SseDecode for Option<String> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        if (<bool>::sse_decode(deserializer)) {
            return Some(<String>::sse_decode(deserializer));
        } else {
            return None;
        }
    }
}

impl SseDecode for Option<crate::rules_ir::normalized_model::ContentModel> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        if (<bool>::sse_decode(deserializer)) {
            return Some(
                <crate::rules_ir::normalized_model::ContentModel>::sse_decode(deserializer),
            );
        } else {
            return None;
        }
    }
}

impl SseDecode for Option<crate::rules_ir::normalized_model::DetailModel> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        if (<bool>::sse_decode(deserializer)) {
            return Some(
                <crate::rules_ir::normalized_model::DetailModel>::sse_decode(deserializer),
            );
        } else {
            return None;
        }
    }
}

impl SseDecode for Option<crate::ffi::FfiExecuteContext> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        if (<bool>::sse_decode(deserializer)) {
            return Some(<crate::ffi::FfiExecuteContext>::sse_decode(deserializer));
        } else {
            return None;
        }
    }
}

impl SseDecode for Option<crate::ffi::FfiExecuteError> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        if (<bool>::sse_decode(deserializer)) {
            return Some(<crate::ffi::FfiExecuteError>::sse_decode(deserializer));
        } else {
            return None;
        }
    }
}

impl SseDecode for Option<i32> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        if (<bool>::sse_decode(deserializer)) {
            return Some(<i32>::sse_decode(deserializer));
        } else {
            return None;
        }
    }
}

impl SseDecode for Option<crate::rules_ir::normalized_model::MediaExtension> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        if (<bool>::sse_decode(deserializer)) {
            return Some(
                <crate::rules_ir::normalized_model::MediaExtension>::sse_decode(deserializer),
            );
        } else {
            return None;
        }
    }
}

impl SseDecode for Option<crate::rules_ir::normalized_model::MediaSpec> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        if (<bool>::sse_decode(deserializer)) {
            return Some(<crate::rules_ir::normalized_model::MediaSpec>::sse_decode(
                deserializer,
            ));
        } else {
            return None;
        }
    }
}

impl SseDecode for Option<crate::rules_ir::normalized_model::SearchModel> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        if (<bool>::sse_decode(deserializer)) {
            return Some(
                <crate::rules_ir::normalized_model::SearchModel>::sse_decode(deserializer),
            );
        } else {
            return None;
        }
    }
}

impl SseDecode for Option<crate::rules_ir::normalized_model::TocModel> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        if (<bool>::sse_decode(deserializer)) {
            return Some(<crate::rules_ir::normalized_model::TocModel>::sse_decode(
                deserializer,
            ));
        } else {
            return None;
        }
    }
}

impl SseDecode for (String, String) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut var_field0 = <String>::sse_decode(deserializer);
        let mut var_field1 = <String>::sse_decode(deserializer);
        return (var_field0, var_field1);
    }
}

impl SseDecode for crate::rules_ir::normalized_model::SearchItem {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut var_title = <String>::sse_decode(deserializer);
        let mut var_url = <String>::sse_decode(deserializer);
        let mut var_cover = <Option<String>>::sse_decode(deserializer);
        let mut var_author = <Option<String>>::sse_decode(deserializer);
        return crate::rules_ir::normalized_model::SearchItem {
            title: var_title,
            url: var_url,
            cover: var_cover,
            author: var_author,
        };
    }
}

impl SseDecode for crate::rules_ir::normalized_model::SearchModel {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut var_items =
            <Vec<crate::rules_ir::normalized_model::SearchItem>>::sse_decode(deserializer);
        return crate::rules_ir::normalized_model::SearchModel { items: var_items };
    }
}

impl SseDecode for crate::rules_ir::normalized_model::TocModel {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut var_chapters =
            <Vec<crate::rules_ir::normalized_model::ChapterItem>>::sse_decode(deserializer);
        return crate::rules_ir::normalized_model::TocModel {
            chapters: var_chapters,
        };
    }
}

impl SseDecode for u8 {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        deserializer.cursor.read_u8().unwrap()
    }
}

impl SseDecode for () {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {}
}

fn pde_ffi_dispatcher_primary_impl(
    func_id: i32,
    port: flutter_rust_bridge::for_generated::MessagePort,
    ptr: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len: i32,
    data_len: i32,
) {
    // Codec=Pde (Serialization + dispatch), see doc to use other codecs
    match func_id {
        1 => wire__crate__ffi__execute_rule_impl(port, ptr, rust_vec_len, data_len),
        2 => wire__crate__ffi__ffi_execute_context_default_impl(port, ptr, rust_vec_len, data_len),
        _ => unreachable!(),
    }
}

fn pde_ffi_dispatcher_sync_impl(
    func_id: i32,
    ptr: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len: i32,
    data_len: i32,
) -> flutter_rust_bridge::for_generated::WireSyncRust2DartSse {
    // Codec=Pde (Serialization + dispatch), see doc to use other codecs
    match func_id {
        3 => wire__crate__ffi__ping_impl(ptr, rust_vec_len, data_len),
        4 => wire__crate__ffi__validate_rule_impl(ptr, rust_vec_len, data_len),
        _ => unreachable!(),
    }
}

// Section: rust2dart

// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for crate::rules_ir::normalized_model::ChapterItem {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        [
            self.title.into_into_dart().into_dart(),
            self.url.into_into_dart().into_dart(),
        ]
        .into_dart()
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive
    for crate::rules_ir::normalized_model::ChapterItem
{
}
impl flutter_rust_bridge::IntoIntoDart<crate::rules_ir::normalized_model::ChapterItem>
    for crate::rules_ir::normalized_model::ChapterItem
{
    fn into_into_dart(self) -> crate::rules_ir::normalized_model::ChapterItem {
        self
    }
}
// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for crate::rules_ir::normalized_model::ContentModel {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        [
            self.content_text_html.into_into_dart().into_dart(),
            self.content_text_plain.into_into_dart().into_dart(),
            self.media_assets.into_into_dart().into_dart(),
        ]
        .into_dart()
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive
    for crate::rules_ir::normalized_model::ContentModel
{
}
impl flutter_rust_bridge::IntoIntoDart<crate::rules_ir::normalized_model::ContentModel>
    for crate::rules_ir::normalized_model::ContentModel
{
    fn into_into_dart(self) -> crate::rules_ir::normalized_model::ContentModel {
        self
    }
}
// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for crate::rules_ir::normalized_model::DetailModel {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        [
            self.title.into_into_dart().into_dart(),
            self.cover.into_into_dart().into_dart(),
            self.author.into_into_dart().into_dart(),
            self.description.into_into_dart().into_dart(),
            self.tags.into_into_dart().into_dart(),
        ]
        .into_dart()
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive
    for crate::rules_ir::normalized_model::DetailModel
{
}
impl flutter_rust_bridge::IntoIntoDart<crate::rules_ir::normalized_model::DetailModel>
    for crate::rules_ir::normalized_model::DetailModel
{
    fn into_into_dart(self) -> crate::rules_ir::normalized_model::DetailModel {
        self
    }
}
// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for crate::ffi::FfiDiagnostic {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        [
            self.code.into_into_dart().into_dart(),
            self.path.into_into_dart().into_dart(),
            self.message.into_into_dart().into_dart(),
            self.node_id.into_into_dart().into_dart(),
        ]
        .into_dart()
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive for crate::ffi::FfiDiagnostic {}
impl flutter_rust_bridge::IntoIntoDart<crate::ffi::FfiDiagnostic> for crate::ffi::FfiDiagnostic {
    fn into_into_dart(self) -> crate::ffi::FfiDiagnostic {
        self
    }
}
// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for crate::ffi::FfiExecuteContext {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        [
            self.run_id.into_into_dart().into_dart(),
            self.trace_id.into_into_dart().into_dart(),
            self.channel_capacity.into_into_dart().into_dart(),
            self.rule_id.into_into_dart().into_dart(),
            self.rule_kv_json.into_into_dart().into_dart(),
            self.cookie_jar_json.into_into_dart().into_dart(),
        ]
        .into_dart()
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive for crate::ffi::FfiExecuteContext {}
impl flutter_rust_bridge::IntoIntoDart<crate::ffi::FfiExecuteContext>
    for crate::ffi::FfiExecuteContext
{
    fn into_into_dart(self) -> crate::ffi::FfiExecuteContext {
        self
    }
}
// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for crate::ffi::FfiExecuteError {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        [
            self.code.into_into_dart().into_dart(),
            self.message.into_into_dart().into_dart(),
            self.diagnostics.into_into_dart().into_dart(),
        ]
        .into_dart()
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive for crate::ffi::FfiExecuteError {}
impl flutter_rust_bridge::IntoIntoDart<crate::ffi::FfiExecuteError>
    for crate::ffi::FfiExecuteError
{
    fn into_into_dart(self) -> crate::ffi::FfiExecuteError {
        self
    }
}
// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for crate::ffi::FfiExecuteResponse {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        [
            self.run_id.into_into_dart().into_dart(),
            self.initial_result_json.into_into_dart().into_dart(),
            self.error.into_into_dart().into_dart(),
            self.rule_kv_json.into_into_dart().into_dart(),
            self.cookie_jar_json.into_into_dart().into_dart(),
        ]
        .into_dart()
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive
    for crate::ffi::FfiExecuteResponse
{
}
impl flutter_rust_bridge::IntoIntoDart<crate::ffi::FfiExecuteResponse>
    for crate::ffi::FfiExecuteResponse
{
    fn into_into_dart(self) -> crate::ffi::FfiExecuteResponse {
        self
    }
}
// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for crate::ffi::FfiValidationResult {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        [
            self.valid.into_into_dart().into_dart(),
            self.diagnostics.into_into_dart().into_dart(),
        ]
        .into_dart()
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive
    for crate::ffi::FfiValidationResult
{
}
impl flutter_rust_bridge::IntoIntoDart<crate::ffi::FfiValidationResult>
    for crate::ffi::FfiValidationResult
{
    fn into_into_dart(self) -> crate::ffi::FfiValidationResult {
        self
    }
}
// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for crate::rules_ir::normalized_model::MediaAsset {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        [
            self.media_type.into_into_dart().into_dart(),
            self.url.into_into_dart().into_dart(),
            self.title.into_into_dart().into_dart(),
            self.cover.into_into_dart().into_dart(),
        ]
        .into_dart()
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive
    for crate::rules_ir::normalized_model::MediaAsset
{
}
impl flutter_rust_bridge::IntoIntoDart<crate::rules_ir::normalized_model::MediaAsset>
    for crate::rules_ir::normalized_model::MediaAsset
{
    fn into_into_dart(self) -> crate::rules_ir::normalized_model::MediaAsset {
        self
    }
}
// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for crate::rules_ir::normalized_model::MediaExtension {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        [
            self.video.into_into_dart().into_dart(),
            self.music.into_into_dart().into_dart(),
            self.novel.into_into_dart().into_dart(),
            self.comic.into_into_dart().into_dart(),
            self.image.into_into_dart().into_dart(),
        ]
        .into_dart()
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive
    for crate::rules_ir::normalized_model::MediaExtension
{
}
impl flutter_rust_bridge::IntoIntoDart<crate::rules_ir::normalized_model::MediaExtension>
    for crate::rules_ir::normalized_model::MediaExtension
{
    fn into_into_dart(self) -> crate::rules_ir::normalized_model::MediaExtension {
        self
    }
}
// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for crate::rules_ir::normalized_model::MediaSpec {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        [self.extra.into_into_dart().into_dart()].into_dart()
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive
    for crate::rules_ir::normalized_model::MediaSpec
{
}
impl flutter_rust_bridge::IntoIntoDart<crate::rules_ir::normalized_model::MediaSpec>
    for crate::rules_ir::normalized_model::MediaSpec
{
    fn into_into_dart(self) -> crate::rules_ir::normalized_model::MediaSpec {
        self
    }
}
// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for crate::rules_ir::normalized_model::MediaType {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        match self {
            Self::Video => 0.into_dart(),
            Self::Music => 1.into_dart(),
            Self::Novel => 2.into_dart(),
            Self::Comic => 3.into_dart(),
            Self::Image => 4.into_dart(),
            _ => unreachable!(),
        }
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive
    for crate::rules_ir::normalized_model::MediaType
{
}
impl flutter_rust_bridge::IntoIntoDart<crate::rules_ir::normalized_model::MediaType>
    for crate::rules_ir::normalized_model::MediaType
{
    fn into_into_dart(self) -> crate::rules_ir::normalized_model::MediaType {
        self
    }
}
// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for crate::rules_ir::normalized_model::NormalizedModel {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        [
            self.search.into_into_dart().into_dart(),
            self.detail.into_into_dart().into_dart(),
            self.toc.into_into_dart().into_dart(),
            self.content.into_into_dart().into_dart(),
            self.media.into_into_dart().into_dart(),
        ]
        .into_dart()
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive
    for crate::rules_ir::normalized_model::NormalizedModel
{
}
impl flutter_rust_bridge::IntoIntoDart<crate::rules_ir::normalized_model::NormalizedModel>
    for crate::rules_ir::normalized_model::NormalizedModel
{
    fn into_into_dart(self) -> crate::rules_ir::normalized_model::NormalizedModel {
        self
    }
}
// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for crate::rules_ir::normalized_model::SearchItem {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        [
            self.title.into_into_dart().into_dart(),
            self.url.into_into_dart().into_dart(),
            self.cover.into_into_dart().into_dart(),
            self.author.into_into_dart().into_dart(),
        ]
        .into_dart()
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive
    for crate::rules_ir::normalized_model::SearchItem
{
}
impl flutter_rust_bridge::IntoIntoDart<crate::rules_ir::normalized_model::SearchItem>
    for crate::rules_ir::normalized_model::SearchItem
{
    fn into_into_dart(self) -> crate::rules_ir::normalized_model::SearchItem {
        self
    }
}
// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for crate::rules_ir::normalized_model::SearchModel {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        [self.items.into_into_dart().into_dart()].into_dart()
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive
    for crate::rules_ir::normalized_model::SearchModel
{
}
impl flutter_rust_bridge::IntoIntoDart<crate::rules_ir::normalized_model::SearchModel>
    for crate::rules_ir::normalized_model::SearchModel
{
    fn into_into_dart(self) -> crate::rules_ir::normalized_model::SearchModel {
        self
    }
}
// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for crate::rules_ir::normalized_model::TocModel {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        [self.chapters.into_into_dart().into_dart()].into_dart()
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive
    for crate::rules_ir::normalized_model::TocModel
{
}
impl flutter_rust_bridge::IntoIntoDart<crate::rules_ir::normalized_model::TocModel>
    for crate::rules_ir::normalized_model::TocModel
{
    fn into_into_dart(self) -> crate::rules_ir::normalized_model::TocModel {
        self
    }
}

impl SseEncode for std::collections::HashMap<String, String> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <Vec<(String, String)>>::sse_encode(self.into_iter().collect(), serializer);
    }
}

impl SseEncode for String {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <Vec<u8>>::sse_encode(self.into_bytes(), serializer);
    }
}

impl SseEncode for bool {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        serializer.cursor.write_u8(self as _).unwrap();
    }
}

impl SseEncode for crate::rules_ir::normalized_model::ChapterItem {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <String>::sse_encode(self.title, serializer);
        <Option<String>>::sse_encode(self.url, serializer);
    }
}

impl SseEncode for crate::rules_ir::normalized_model::ContentModel {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <Option<String>>::sse_encode(self.content_text_html, serializer);
        <Option<String>>::sse_encode(self.content_text_plain, serializer);
        <Vec<crate::rules_ir::normalized_model::MediaAsset>>::sse_encode(
            self.media_assets,
            serializer,
        );
    }
}

impl SseEncode for crate::rules_ir::normalized_model::DetailModel {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <String>::sse_encode(self.title, serializer);
        <Option<String>>::sse_encode(self.cover, serializer);
        <Option<String>>::sse_encode(self.author, serializer);
        <Option<String>>::sse_encode(self.description, serializer);
        <Vec<String>>::sse_encode(self.tags, serializer);
    }
}

impl SseEncode for crate::ffi::FfiDiagnostic {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <String>::sse_encode(self.code, serializer);
        <String>::sse_encode(self.path, serializer);
        <String>::sse_encode(self.message, serializer);
        <Option<String>>::sse_encode(self.node_id, serializer);
    }
}

impl SseEncode for crate::ffi::FfiExecuteContext {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <Option<String>>::sse_encode(self.run_id, serializer);
        <Option<String>>::sse_encode(self.trace_id, serializer);
        <Option<i32>>::sse_encode(self.channel_capacity, serializer);
        <Option<String>>::sse_encode(self.rule_id, serializer);
        <Option<String>>::sse_encode(self.rule_kv_json, serializer);
        <Option<String>>::sse_encode(self.cookie_jar_json, serializer);
    }
}

impl SseEncode for crate::ffi::FfiExecuteError {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <String>::sse_encode(self.code, serializer);
        <String>::sse_encode(self.message, serializer);
        <Vec<crate::ffi::FfiDiagnostic>>::sse_encode(self.diagnostics, serializer);
    }
}

impl SseEncode for crate::ffi::FfiExecuteResponse {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <Option<String>>::sse_encode(self.run_id, serializer);
        <Option<String>>::sse_encode(self.initial_result_json, serializer);
        <Option<crate::ffi::FfiExecuteError>>::sse_encode(self.error, serializer);
        <Option<String>>::sse_encode(self.rule_kv_json, serializer);
        <Option<String>>::sse_encode(self.cookie_jar_json, serializer);
    }
}

impl SseEncode for crate::ffi::FfiValidationResult {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <bool>::sse_encode(self.valid, serializer);
        <Vec<crate::ffi::FfiDiagnostic>>::sse_encode(self.diagnostics, serializer);
    }
}

impl SseEncode for i32 {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        serializer.cursor.write_i32::<NativeEndian>(self).unwrap();
    }
}

impl SseEncode for Vec<String> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <i32>::sse_encode(self.len() as _, serializer);
        for item in self {
            <String>::sse_encode(item, serializer);
        }
    }
}

impl SseEncode for Vec<crate::rules_ir::normalized_model::ChapterItem> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <i32>::sse_encode(self.len() as _, serializer);
        for item in self {
            <crate::rules_ir::normalized_model::ChapterItem>::sse_encode(item, serializer);
        }
    }
}

impl SseEncode for Vec<crate::ffi::FfiDiagnostic> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <i32>::sse_encode(self.len() as _, serializer);
        for item in self {
            <crate::ffi::FfiDiagnostic>::sse_encode(item, serializer);
        }
    }
}

impl SseEncode for Vec<crate::rules_ir::normalized_model::MediaAsset> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <i32>::sse_encode(self.len() as _, serializer);
        for item in self {
            <crate::rules_ir::normalized_model::MediaAsset>::sse_encode(item, serializer);
        }
    }
}

impl SseEncode for Vec<u8> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <i32>::sse_encode(self.len() as _, serializer);
        for item in self {
            <u8>::sse_encode(item, serializer);
        }
    }
}

impl SseEncode for Vec<(String, String)> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <i32>::sse_encode(self.len() as _, serializer);
        for item in self {
            <(String, String)>::sse_encode(item, serializer);
        }
    }
}

impl SseEncode for Vec<crate::rules_ir::normalized_model::SearchItem> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <i32>::sse_encode(self.len() as _, serializer);
        for item in self {
            <crate::rules_ir::normalized_model::SearchItem>::sse_encode(item, serializer);
        }
    }
}

impl SseEncode for crate::rules_ir::normalized_model::MediaAsset {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <crate::rules_ir::normalized_model::MediaType>::sse_encode(self.media_type, serializer);
        <String>::sse_encode(self.url, serializer);
        <Option<String>>::sse_encode(self.title, serializer);
        <Option<String>>::sse_encode(self.cover, serializer);
    }
}

impl SseEncode for crate::rules_ir::normalized_model::MediaExtension {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <Option<crate::rules_ir::normalized_model::MediaSpec>>::sse_encode(self.video, serializer);
        <Option<crate::rules_ir::normalized_model::MediaSpec>>::sse_encode(self.music, serializer);
        <Option<crate::rules_ir::normalized_model::MediaSpec>>::sse_encode(self.novel, serializer);
        <Option<crate::rules_ir::normalized_model::MediaSpec>>::sse_encode(self.comic, serializer);
        <Option<crate::rules_ir::normalized_model::MediaSpec>>::sse_encode(self.image, serializer);
    }
}

impl SseEncode for crate::rules_ir::normalized_model::MediaSpec {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <std::collections::HashMap<String, String>>::sse_encode(self.extra, serializer);
    }
}

impl SseEncode for crate::rules_ir::normalized_model::MediaType {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <i32>::sse_encode(
            match self {
                crate::rules_ir::normalized_model::MediaType::Video => 0,
                crate::rules_ir::normalized_model::MediaType::Music => 1,
                crate::rules_ir::normalized_model::MediaType::Novel => 2,
                crate::rules_ir::normalized_model::MediaType::Comic => 3,
                crate::rules_ir::normalized_model::MediaType::Image => 4,
                _ => {
                    unimplemented!("");
                }
            },
            serializer,
        );
    }
}

impl SseEncode for crate::rules_ir::normalized_model::NormalizedModel {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <Option<crate::rules_ir::normalized_model::SearchModel>>::sse_encode(
            self.search,
            serializer,
        );
        <Option<crate::rules_ir::normalized_model::DetailModel>>::sse_encode(
            self.detail,
            serializer,
        );
        <Option<crate::rules_ir::normalized_model::TocModel>>::sse_encode(self.toc, serializer);
        <Option<crate::rules_ir::normalized_model::ContentModel>>::sse_encode(
            self.content,
            serializer,
        );
        <Option<crate::rules_ir::normalized_model::MediaExtension>>::sse_encode(
            self.media, serializer,
        );
    }
}

impl SseEncode for Option<String> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <bool>::sse_encode(self.is_some(), serializer);
        if let Some(value) = self {
            <String>::sse_encode(value, serializer);
        }
    }
}

impl SseEncode for Option<crate::rules_ir::normalized_model::ContentModel> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <bool>::sse_encode(self.is_some(), serializer);
        if let Some(value) = self {
            <crate::rules_ir::normalized_model::ContentModel>::sse_encode(value, serializer);
        }
    }
}

impl SseEncode for Option<crate::rules_ir::normalized_model::DetailModel> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <bool>::sse_encode(self.is_some(), serializer);
        if let Some(value) = self {
            <crate::rules_ir::normalized_model::DetailModel>::sse_encode(value, serializer);
        }
    }
}

impl SseEncode for Option<crate::ffi::FfiExecuteContext> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <bool>::sse_encode(self.is_some(), serializer);
        if let Some(value) = self {
            <crate::ffi::FfiExecuteContext>::sse_encode(value, serializer);
        }
    }
}

impl SseEncode for Option<crate::ffi::FfiExecuteError> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <bool>::sse_encode(self.is_some(), serializer);
        if let Some(value) = self {
            <crate::ffi::FfiExecuteError>::sse_encode(value, serializer);
        }
    }
}

impl SseEncode for Option<i32> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <bool>::sse_encode(self.is_some(), serializer);
        if let Some(value) = self {
            <i32>::sse_encode(value, serializer);
        }
    }
}

impl SseEncode for Option<crate::rules_ir::normalized_model::MediaExtension> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <bool>::sse_encode(self.is_some(), serializer);
        if let Some(value) = self {
            <crate::rules_ir::normalized_model::MediaExtension>::sse_encode(value, serializer);
        }
    }
}

impl SseEncode for Option<crate::rules_ir::normalized_model::MediaSpec> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <bool>::sse_encode(self.is_some(), serializer);
        if let Some(value) = self {
            <crate::rules_ir::normalized_model::MediaSpec>::sse_encode(value, serializer);
        }
    }
}

impl SseEncode for Option<crate::rules_ir::normalized_model::SearchModel> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <bool>::sse_encode(self.is_some(), serializer);
        if let Some(value) = self {
            <crate::rules_ir::normalized_model::SearchModel>::sse_encode(value, serializer);
        }
    }
}

impl SseEncode for Option<crate::rules_ir::normalized_model::TocModel> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <bool>::sse_encode(self.is_some(), serializer);
        if let Some(value) = self {
            <crate::rules_ir::normalized_model::TocModel>::sse_encode(value, serializer);
        }
    }
}

impl SseEncode for (String, String) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <String>::sse_encode(self.0, serializer);
        <String>::sse_encode(self.1, serializer);
    }
}

impl SseEncode for crate::rules_ir::normalized_model::SearchItem {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <String>::sse_encode(self.title, serializer);
        <String>::sse_encode(self.url, serializer);
        <Option<String>>::sse_encode(self.cover, serializer);
        <Option<String>>::sse_encode(self.author, serializer);
    }
}

impl SseEncode for crate::rules_ir::normalized_model::SearchModel {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <Vec<crate::rules_ir::normalized_model::SearchItem>>::sse_encode(self.items, serializer);
    }
}

impl SseEncode for crate::rules_ir::normalized_model::TocModel {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <Vec<crate::rules_ir::normalized_model::ChapterItem>>::sse_encode(
            self.chapters,
            serializer,
        );
    }
}

impl SseEncode for u8 {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        serializer.cursor.write_u8(self).unwrap();
    }
}

impl SseEncode for () {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {}
}

#[cfg(not(target_family = "wasm"))]
mod io {
    // This file is automatically generated, so please do not edit it.
    // @generated by `flutter_rust_bridge`@ 2.11.1.

    // Section: imports

    use flutter_rust_bridge::{
        Handler, IntoIntoDart,
        for_generated::{
            Lifetimeable, Lockable,
            byteorder::{NativeEndian, ReadBytesExt, WriteBytesExt},
            transform_result_dco,
        },
    };

    use super::*;

    // Section: boilerplate

    flutter_rust_bridge::frb_generated_boilerplate_io!();
}
#[cfg(not(target_family = "wasm"))]
pub use io::*;

/// cbindgen:ignore
#[cfg(target_family = "wasm")]
mod web {
    // This file is automatically generated, so please do not edit it.
    // @generated by `flutter_rust_bridge`@ 2.11.1.

    // Section: imports

    use flutter_rust_bridge::{
        Handler, IntoIntoDart,
        for_generated::{
            Lifetimeable, Lockable,
            byteorder::{NativeEndian, ReadBytesExt, WriteBytesExt},
            transform_result_dco, wasm_bindgen,
            wasm_bindgen::prelude::*,
        },
    };

    use super::*;

    // Section: boilerplate

    flutter_rust_bridge::frb_generated_boilerplate_web!();
}
#[cfg(target_family = "wasm")]
pub use web::*;
