// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../domain/rule/crawler_rule.dart';
import '../domain/rule/lifecycle.dart';
import '../domain/rule/network.dart';
import '../domain/rule/pipeline.dart';
import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

Future<bool> validateRule({required CrawlerRule rule}) =>
    RustLib.instance.api.crateApiCrawlerModelsValidateRule(rule: rule);

Future<PipelineGraph> createEmptyPipeline() =>
    RustLib.instance.api.crateApiCrawlerModelsCreateEmptyPipeline();
