// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../domain/rule/pipeline.dart';
import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `execute_operation`, `execute_pipeline_internal`, `parse_html_internal`

/// 解析 HTML 并执行单个选择器查询
///
/// # 参数
/// - `html`: HTML 文档字符串
/// - `selector_type`: 选择器类型 ("xpath", "css", "jsonpath", "regex")
/// - `query`: 查询表达式
///
/// # 返回
/// 匹配结果的字符串数组
List<String> parseHtml({
  required String html,
  required String selectorType,
  required String query,
}) => RustLib.instance.api.crateApiHtmlParserParseHtml(
  html: html,
  selectorType: selectorType,
  query: query,
);

/// 执行完整的 Pipeline 操作序列
///
/// # 参数
/// - `request`: Pipeline 执行请求
///
/// # 返回
/// Pipeline 执行结果
PipelineExecuteResult executePipeline({
  required PipelineExecuteRequest request,
}) => RustLib.instance.api.crateApiHtmlParserExecutePipeline(request: request);

/// 执行 CSS 选择器并提取属性
///
/// # 参数
/// - `html`: HTML 文档字符串
/// - `selector`: CSS 选择器
/// - `attr`: 属性名
///
/// # 返回
/// 匹配元素的属性值数组
List<String> cssSelectAttr({
  required String html,
  required String selector,
  required String attr,
}) => RustLib.instance.api.crateApiHtmlParserCssSelectAttr(
  html: html,
  selector: selector,
  attr: attr,
);

/// 执行 JavaScript 代码
///
/// # 参数
/// - `script`: JavaScript 代码
/// - `val`: 当前值
/// - `vars_json`: 上下文变量 (JSON 字符串)
///
/// # 返回
/// 执行结果
String executeJs({
  required String script,
  required String val,
  String? varsJson,
}) => RustLib.instance.api.crateApiHtmlParserExecuteJs(
  script: script,
  val: val,
  varsJson: varsJson,
);
