// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../domain/phase.dart';
import '../domain/rule/crawler_rule.dart';
import '../domain/rule/lifecycle.dart';
import '../domain/rule/network.dart';
import '../domain/rule/pipeline.dart';
import '../error.dart';
import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `build_http_request`, `build_phase_operations`, `build_phase_url`, `contextual_url_placeholder`, `convert_to_phase_data`, `detect_content_type`, `encode_url_component`, `execute_lifecycle_phase_with_fetcher`, `get_phase_url_template`, `is_waf_intercepted`, `map_emulation_type`, `parse_content_type_name`, `sort_pipeline_nodes`, `validate_selector_for_content_type`

/// 执行指定生命周期阶段并返回结构化结果
Future<PhaseResult> executeLifecyclePhase({
  required CrawlerRule rule,
  required LifecyclePhase phase,
  required PhaseContext context,
}) => RustLib.instance.api.crateApiLifecycleExecutorExecuteLifecyclePhase(
  rule: rule,
  phase: phase,
  context: context,
);
