// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `get_metadata_regexes`, `get_whitespace_regex`

/// 计算 Jaccard 相似度
///
/// 基于中文分词计算两个字符串的 Jaccard 相似度
///
/// # Arguments
/// * `a` - 第一个字符串
/// * `b` - 第二个字符串
///
/// # Returns
/// 相似度值 (0.0 ~ 1.0)
Future<double> jaccard({required String a, required String b}) =>
    RustLib.instance.api.crateApiSimilarityJaccard(a: a, b: b);

/// 计算 Levenshtein 相似度
///
/// 使用 textdistance 库计算编辑距离相似度
///
/// # Arguments
/// * `a` - 第一个字符串
/// * `b` - 第二个字符串
///
/// # Returns
/// 相似度值 (0.0 ~ 1.0)
Future<double> levenshtein({required String a, required String b}) =>
    RustLib.instance.api.crateApiSimilarityLevenshtein(a: a, b: b);

/// 计算 Sørensen-Dice 相似度
///
/// 基于中文分词计算词组序列的 Sørensen-Dice 相似度
/// 比 Jaccard 更强调共同元素
///
/// # Arguments
/// * `a` - 第一个字符串
/// * `b` - 第二个字符串
///
/// # Returns
/// 相似度值 (0.0 ~ 1.0)
Future<double> sorensenDice({required String a, required String b}) =>
    RustLib.instance.api.crateApiSimilaritySorensenDice(a: a, b: b);

/// 计算词组序列的 Levenshtein 相似度
///
/// 基于中文分词后计算词组序列的编辑距离相似度
/// 对词序敏感，适合标题匹配
///
/// # Arguments
/// * `a` - 第一个字符串
/// * `b` - 第二个字符串
///
/// # Returns
/// 相似度值 (0.0 ~ 1.0)
Future<double> levenshteinTokens({required String a, required String b}) =>
    RustLib.instance.api.crateApiSimilarityLevenshteinTokens(a: a, b: b);

/// 标题标准化
///
/// 统一标题格式：
/// 1. 繁体转简体
/// 2. 去除元数据模式
/// 3. 转小写
/// 4. 合并空白
///
/// # Arguments
/// * `title` - 原始标题
///
/// # Returns
/// 标准化后的标题
Future<String> normalizeTitle({required String title}) =>
    RustLib.instance.api.crateApiSimilarityNormalizeTitle(title: title);

/// 模糊搜索评分
///
/// 综合计算搜索词与目标标题的相似度
/// 算法: sorensen_dice * 0.4 + levenshtein_tokens * 0.4 + levenshtein * 0.2
///
/// # Arguments
/// * `query` - 搜索词
/// * `target` - 目标标题
///
/// # Returns
/// 综合相似度分数 (0.0 ~ 1.0)
Future<double> fuzzySearchScore({
  required String query,
  required String target,
}) => RustLib.instance.api.crateApiSimilarityFuzzySearchScore(
  query: query,
  target: target,
);
