// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `get_opencc_s2t`, `get_opencc_t2s`

Future<void> getJieba() => RustLib.instance.api.crateApiTextProcessorGetJieba();

/// 中文分词
///
/// 使用 jieba 进行中文分词
///
/// # Arguments
/// * `text` - 待分词的文本
///
/// # Returns
/// 分词结果列表
Future<List<String>> segment({required String text}) =>
    RustLib.instance.api.crateApiTextProcessorSegment(text: text);

/// 繁体转简体
///
/// 将繁体中文转换为简体中文
///
/// # Arguments
/// * `text` - 待转换的繁体文本
///
/// # Returns
/// 转换后的简体文本
Future<String> toSimplified({required String text}) =>
    RustLib.instance.api.crateApiTextProcessorToSimplified(text: text);

/// 简体转繁体
///
/// 将简体中文转换为繁体中文
///
/// # Arguments
/// * `text` - 待转换的简体文本
///
/// # Returns
/// 转换后的繁体文本
Future<String> toTraditional({required String text}) =>
    RustLib.instance.api.crateApiTextProcessorToTraditional(text: text);

/// 数字转中文
///
/// 将阿拉伯数字转换为中文数字
///
/// # Arguments
/// * `number` - 待转换的数字
///
/// # Returns
/// 中文数字字符串
Future<String> numberToChinese({required int number}) =>
    RustLib.instance.api.crateApiTextProcessorNumberToChinese(number: number);
