// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * 规则能力声明。
 */
export type Capabilities = { 
/**
 * 是否支持分页。
 */
supportsPagination: boolean, 
/**
 * 是否支持并发抓取。
 */
supportsConcurrency: boolean, 
/**
 * 是否需要认证。
 */
requiresAuth: boolean, };
