// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * 节点布局信息。
 */
export type NodeLayout = { 
/**
 * X 轴坐标。
 */
x: number, 
/**
 * Y 轴坐标。
 */
y: number, };
