// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DataType } from "./DataType";

/**
 * 记录类型字段定义。
 */
export type RecordField = { 
/**
 * 字段名。
 */
name: string, 
/**
 * 字段类型。
 */
dataType: DataType, 
/**
 * 是否可选。
 */
optional: boolean, };
