// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CryptoCapabilities } from "./CryptoCapabilities";

/**
 * 规则能力声明。
 */
export type Capabilities = { 
/**
 * 是否支持分页。
 */
supportsPagination: boolean, 
/**
 * 是否支持并发抓取。
 */
supportsConcurrency: boolean, 
/**
 * 是否需要认证。
 */
requiresAuth: boolean, 
/**
 * 是否允许使用 JS transform。
 */
supportsJs: boolean, 
/**
 * 是否允许使用 codec 族 transform。
 */
codec: boolean, 
/**
 * 是否允许使用加密能力。
 */
crypto: CryptoCapabilities, 
/**
 * 是否允许在规则内联密钥/密文参数。
 */
allowInlineSecrets: boolean, };
