// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * 章节项模型。
 */
export type ChapterItem = {
  /**
   * 章节标题。
   */
  title: string;
  /**
   * 章节链接。
   */
  url?: string | null;
};
