// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { MediaAsset } from "./MediaAsset";

/**
 * 内容阶段模型。
 */
export type ContentModel = { 
/**
 * HTML 文本内容。
 */
contentTextHtml?: string | null, 
/**
 * 纯文本内容。
 */
contentTextPlain?: string | null, 
/**
 * 媒体资源。
 */
mediaAssets: Array<MediaAsset>, };
