// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * 规则加密能力声明。
 */
export type CryptoCapabilities = {
  /**
   * 是否允许使用 AES 变换。
   */
  aes: boolean;
};
