// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { RecordField } from "./RecordField";

/**
 * 数据类型系统。
 */
export type DataType = { "type": "text" } | { "type": "html" } | { "type": "json" } | { "type": "url" } | { "type": "list", item: DataType, } | { "type": "record", fields: Array<RecordField>, } | { "type": "normalizedModel" };
