// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PortRef } from "./PortRef";

/**
 * 边定义。
 */
export type Edge = { 
/**
 * 起点端口。
 */
from: PortRef, 
/**
 * 终点端口。
 */
to: PortRef, };
