// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { NodeLayout } from './NodeLayout';

/**
 * 图布局信息。
 */
export type GraphLayout = {
  /**
   * 节点布局信息。
   */
  nodes: { [key in string]: NodeLayout };
};
