// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Edge } from './Edge';
import type { GraphLayout } from './GraphLayout';
import type { GraphMetadata } from './GraphMetadata';
import type { LifecyclePhase } from './LifecyclePhase';
import type { Node } from './Node';
import type { PortRef } from './PortRef';

/**
 * 规则执行图。
 */
export type Graph = {
  /**
   * 节点集合。
   */
  nodes: Array<Node>;
  /**
   * 边集合。
   */
  edges: Array<Edge>;
  /**
   * 阶段入口端口映射。
   */
  phaseEntrypoints: { [key in LifecyclePhase]?: PortRef };
  /**
   * 图元信息。
   */
  metadata?: GraphMetadata | null;
  /**
   * 图布局信息。
   */
  layout?: GraphLayout | null;
};
