// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { KeyRefProvider } from './KeyRefProvider';

/**
 * 密钥引用（用于避免在规则内直接内联敏感值）。
 */
export type KeyRef = {
  /**
   * 密钥来源。
   */
  provider: KeyRefProvider;
  /**
   * 提供方内的键名（variable / secureStore 使用）。
   */
  name?: string | null;
  /**
   * 内联密钥值（inline 使用）。
   */
  value?: string | null;
};
