// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { MediaType } from "./MediaType";

/**
 * 媒体资源项。
 */
export type MediaAsset = { 
/**
 * 资源类型。
 */
mediaType: MediaType, 
/**
 * 资源链接。
 */
url: string, 
/**
 * 资源标题。
 */
title?: string | null, 
/**
 * 缩略图链接。
 */
cover?: string | null, };
