// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { MediaSpec } from './MediaSpec';

/**
 * 媒体扩展信息。
 */
export type MediaExtension = {
  /**
   * 可选视频扩展。
   */
  video?: MediaSpec | null;
  /**
   * 可选音乐扩展。
   */
  music?: MediaSpec | null;
  /**
   * 可选小说扩展。
   */
  novel?: MediaSpec | null;
  /**
   * 可选漫画扩展。
   */
  comic?: MediaSpec | null;
  /**
   * 可选图片扩展。
   */
  image?: MediaSpec | null;
};
