// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * 通用媒体扩展配置。
 */
export type MediaSpec = { 
/**
 * 附加元数据。
 */
extra: { [key in string]: string }, };
