// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * 媒体类型。
 */
export type MediaType = "video" | "music" | "novel" | "comic" | "image";
