// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * 节点类别。
 */
export type NodeKind =
  | { type: 'fetch' }
  | { type: 'parse' }
  | { type: 'select' }
  | { type: 'transform' }
  | { type: 'cachePut' }
  | { type: 'cacheGet' }
  | { type: 'cookiePut' }
  | { type: 'cookieGet' }
  | { type: 'join' }
  | { type: 'branch' }
  | { type: 'mapToModel' }
  | { type: 'loop' }
  | { type: 'filter' }
  | { type: 'assert' }
  | { type: 'input' }
  | { type: 'extract' }
  | { type: 'normalize' }
  | { type: 'output' };
