// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { LifecyclePhase } from "./LifecyclePhase";
import type { NodeKind } from "./NodeKind";
import type { Port } from "./Port";

/**
 * 执行节点。
 */
export type Node = { 
/**
 * 节点 ID。
 */
id: string, 
/**
 * 节点类型。
 */
kind: NodeKind, 
/**
 * 所属生命周期阶段。
 */
phase: LifecyclePhase, 
/**
 * 输入端口定义。
 */
inputs: Array<Port>, 
/**
 * 输出端口定义。
 */
outputs: Array<Port>, 
/**
 * 节点参数（供运行时节点语义读取）。
 */
params: { [key in string]: string }, };
