// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ContentModel } from './ContentModel';
import type { DetailModel } from './DetailModel';
import type { MediaExtension } from './MediaExtension';
import type { SearchModel } from './SearchModel';
import type { TocModel } from './TocModel';

/**
 * 规则执行的规范化输出模型。
 */
export type NormalizedModel = {
  /**
   * 搜索阶段输出。
   */
  search?: SearchModel | null;
  /**
   * 详情阶段输出。
   */
  detail?: DetailModel | null;
  /**
   * 目录阶段输出。
   */
  toc?: TocModel | null;
  /**
   * 内容阶段输出。
   */
  content?: ContentModel | null;
  /**
   * 媒体扩展输出。
   */
  media?: MediaExtension | null;
};
