// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * 端口引用。
 */
export type PortRef = {
  /**
   * 节点 ID。
   */
  nodeId: string;
  /**
   * 端口名称。
   */
  portName: string;
};
