// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DataType } from './DataType';

/**
 * 端口定义。
 */
export type Port = {
  /**
   * 端口名称。
   */
  name: string;
  /**
   * 端口数据类型。
   */
  dataType: DataType;
  /**
   * 是否可选。
   */
  optional: boolean;
};
