// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * 规则级限速配置。
 */
export type RuleRateLimit = { 
/**
 * 时间窗口内允许的请求数。
 */
count: number, 
/**
 * 时间窗口（毫秒）。
 */
periodMs: bigint, };
