// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * 多源聚合配置
 */
export type AggregationConfig = {
  /**
   * 是否启用聚合
   */
  enabled: boolean;
  /**
   * 源权重 (用于排序)
   */
  weight: number;
  /**
   * 匹配配置
   */
  matching: MatchingConfig;
};

export type AggregationDef =
  | { method: 'First' }
  | { method: 'Last' }
  | { method: 'Join'; separator: string }
  | { method: 'Array' };

/**
 * 内容页配置
 */
export type ContentConfig = {
  /**
   * 数据提取管线
   */
  pipeline: PipelineGraph;
  /**
   * 是否启用媒体嗅探
   */
  sniff_media: boolean;
};

/**
 * 爬虫规则根结构 - 单一数据源 (Single Source of Truth)
 * 此结构将被自动生成 Dart (freezed) 和 TypeScript 接口
 */
export type CrawlerRule = {
  /**
   * 规则唯一标识
   */
  id: string;
  /**
   * 规则名称
   */
  name: string;
  /**
   * 规则描述
   */
  description: string;
  /**
   * 作者
   */
  author: string;
  /**
   * 版本号
   */
  version: string;
  /**
   * 网络配置 (TLS指纹、代理、回退策略等)
   */
  network: NetworkConfig | null;
  /**
   * 多源聚合配置
   */
  aggregation: AggregationConfig | null;
  /**
   * 生命周期配置 (Explore/Search/Detail/Toc/Content)
   */
  lifecycle: Lifecycle;
};

/**
 * 详情页配置
 */
export type DetailConfig = {
  /**
   * 数据提取管线
   */
  pipeline: PipelineGraph;
};

/**
 * 浏览器设备模拟类型
 *
 * 提供常用浏览器的 TLS/HTTP2 指纹伪装，内部映射到 wreq 的具体实现
 */
export type Emulation =
  | 'chrome131'
  | 'chrome132'
  | 'chrome133'
  | 'chrome134'
  | 'chrome135'
  | 'chrome136'
  | 'chrome120'
  | 'chrome124'
  | 'chrome126'
  | 'chrome127'
  | 'chrome128'
  | 'chrome129'
  | 'chrome130'
  | 'safari18'
  | 'safari182'
  | 'safari183'
  | 'safari185'
  | 'safari26'
  | 'safariIos1811'
  | 'firefox133'
  | 'firefox135'
  | 'firefox136'
  | 'firefox139'
  | 'firefox142'
  | 'firefox143'
  | 'firefox144'
  | 'firefox145'
  | 'firefox146'
  | 'firefox147'
  | 'edge127'
  | 'edge131'
  | 'edge134'
  | 'edge135'
  | 'edge136'
  | 'edge137'
  | 'edge138'
  | 'edge139'
  | 'edge140'
  | 'edge141'
  | 'edge142'
  | 'edge143'
  | 'edge144'
  | 'edge145'
  | 'okHttp314'
  | 'okHttp412'
  | 'okHttp5';

/**
 * 操作系统模拟类型
 */
export type EmulationOS = 'windows' | 'macOS' | 'linux' | 'android' | 'iOS';

/**
 * 浏览器模拟高级选项
 */
export type EmulationOption = {
  /**
   * 浏览器版本模拟
   */
  emulation: Emulation | null;
  /**
   * 操作系统模拟
   */
  emulation_os: EmulationOS | null;
  /**
   * 是否跳过 HTTP/2 指纹伪装
   */
  skip_http2: boolean | null;
  /**
   * 是否跳过默认请求头
   */
  skip_headers: boolean | null;
};

/**
 * 发现页配置
 */
export type ExploreConfig = {
  /**
   * 入口 URL
   */
  url: string;
  /**
   * 数据提取管线
   */
  pipeline: PipelineGraph;
};

/**
 * 反爬回退配置
 */
export type FallbackConfig = {
  /**
   * 触发回退的 HTTP 状态码 (如 [403, 503])
   * 使用 Vec<i32> 避免 Dart Uint16List 的 JSON 序列化问题
   */
  trigger_status: Array<number>;
  /**
   * 触发回退的关键词 (如 ["cloudflare", "cf-ray"])
   */
  trigger_keywords: Array<string>;
  /**
   * 回退动作: "webview_interactive" 或 "abort"
   */
  action: string;
};

export type FlowEdge = { id: string; source: string; target: string };

export type FlowNode = { id: string; x: number; y: number; data: NodePayload };

/**
 * 生命周期配置 - 定义爬虫的各个阶段
 */
export type Lifecycle = {
  /**
   * 发现页配置
   */
  explore: ExploreConfig | null;
  /**
   * 搜索页配置
   */
  search: SearchConfig | null;
  /**
   * 详情页配置
   */
  detail: DetailConfig | null;
  /**
   * 目录页配置
   */
  toc: TocConfig | null;
  /**
   * 内容页配置
   */
  content: ContentConfig | null;
};

/**
 * 匹配配置 - 用于多源结果去重
 */
export type MatchingConfig = {
  /**
   * 匹配策略: "exact" 或 "fuzzy"
   */
  strategy: string;
  /**
   * 匹配维度
   */
  dimensions: Array<MatchingDimension>;
};

/**
 * 匹配维度定义
 */
export type MatchingDimension = {
  /**
   * 字段名 (如 "title", "author")
   */
  field: string;
  /**
   * 匹配类型: "exact", "fuzzy", "jaccard"
   */
  match_type: string;
  /**
   * 相似度阈值 (0.0 - 1.0)
   */
  threshold: number;
};

/**
 * 网络配置 - 用户友好的规则级配置
 * 具体的 TLS/HTTP2 指纹伪装由内部 wreq 引擎自动处理
 */
export type NetworkConfig = {
  /**
   * 请求策略: "http" (Rust wreq) 或 "webview" (交互式)
   */
  strategy: string;
  /**
   * 浏览器模拟配置
   */
  emulation: EmulationOption | null;
  /**
   * 连接超时(毫秒)
   */
  connect_timeout: bigint | null;
  /**
   * 读取超时(毫秒)
   */
  read_timeout: bigint | null;
  /**
   * 自定义请求头
   */
  headers: { [key in string]: string } | null;
  /**
   * 代理配置
   */
  proxy: RuleProxyConfig | null;
  /**
   * 反爬回退配置
   */
  fallback: FallbackConfig | null;
};

export type NodePayload =
  | { type: 'Selector'; config: SelectorDef }
  | { type: 'Transform'; config: TransformDef }
  | { type: 'Aggregation'; config: AggregationDef };

/**
 * Pipeline 执行请求
 *
 * 包含执行 Pipeline 所需的所有输入数据
 */
export type PipelineExecuteRequest = {
  /**
   * 输入内容 (HTML/JSON/XML 字符串)
   */
  content: string;
  /**
   * 基础 URL (用于 URL 拼接)
   */
  base_url: string | null;
  /**
   * 上下文变量 (JSON 对象，用于 JS 执行)
   */
  vars: string | null;
  /**
   * 要执行的操作序列 (简化格式)
   */
  operations: Array<PipelineOperation>;
};

/**
 * Pipeline 执行结果
 */
export type PipelineExecuteResult = {
  /**
   * 执行是否成功
   */
  success: boolean;
  /**
   * 结果数据
   */
  data: Array<string>;
  /**
   * 错误信息 (如果有)
   */
  error: string | null;
};

export type PipelineGraph = { nodes: Array<FlowNode>; edges: Array<FlowEdge> };

/**
 * Pipeline 操作定义 (简化格式，用于 FFI 传输)
 */
export type PipelineOperation = {
  /**
   * 操作类型: "xpath", "css", "jsonpath", "regex", "trim", "lower", "upper", "replace", "url", "js", "attr", "text"
   */
  type: string;
  /**
   * 操作参数
   */
  param: string | null;
  /**
   * 第二个参数 (用于 replace 等需要两个参数的操作)
   */
  param2: string | null;
};

/**
 * 规则级代理配置 (简化版，用户友好)
 */
export type RuleProxyConfig = {
  /**
   * 是否启用代理
   */
  enabled: boolean;
  /**
   * HTTP 代理地址 (如 "http://127.0.0.1:7890")
   */
  http: string | null;
  /**
   * HTTPS 代理地址
   */
  https: string | null;
  /**
   * SOCKS5 代理地址 (如 "socks5://127.0.0.1:1080")
   */
  socks5: string | null;
};

/**
 * 搜索页配置
 */
export type SearchConfig = {
  /**
   * 搜索 URL 模板 (支持 {{key}} 变量)
   */
  url: string;
  /**
   * 数据提取管线
   */
  pipeline: PipelineGraph;
};

export type SelectorDef =
  | { method: 'Css'; selector: string }
  | { method: 'XPath'; query: string }
  | { method: 'JsonPath'; path: string }
  | { method: 'Regex'; pattern: string };

/**
 * 目录页配置
 */
export type TocConfig = {
  /**
   * 数据提取管线
   */
  pipeline: PipelineGraph;
};

export type TransformDef =
  | { method: 'Trim' }
  | { method: 'Lower' }
  | { method: 'Upper' }
  | { method: 'RegexReplace'; pattern: string; replace: string }
  | { method: 'Text' }
  | { method: 'Attr'; name: string }
  | { method: 'Url' }
  | { method: 'Js'; script: string };
