// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Capabilities } from './Capabilities';
import type { Graph } from './Graph';
import type { LifecyclePhase } from './LifecyclePhase';
import type { Metadata } from './Metadata';
import type { PortRef } from './PortRef';
import type { RuleRateLimit } from './RuleRateLimit';

/**
 * 规则 IR 顶层版本封套。
 */
export type RuleEnvelope = {
  /**
   * IR 版本号，破坏性变更需升级主版本。
   */
  irVersion: string;
  /**
   * 规则元信息。
   */
  metadata: Metadata;
  /**
   * 有向图结构定义。
   */
  graph: Graph;
  /**
   * 从生命周期阶段到标准化输出端口的映射。
   */
  normalizedOutputs: { [key in LifecyclePhase]?: PortRef };
  /**
   * 规则能力声明。
   */
  capabilities: Capabilities;
  /**
   * 可选规则级限速配置。
   */
  rateLimit?: RuleRateLimit | null;
};
