// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SearchItem } from './SearchItem';

/**
 * 搜索阶段模型。
 */
export type SearchModel = {
  /**
   * 搜索结果列表。
   */
  items: Array<SearchItem>;
};
