// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * 搜索项模型。
 */
export type SearchItem = { 
/**
 * 标题。
 */
title: string, 
/**
 * 链接。
 */
url: string, 
/**
 * 封面。
 */
cover?: string | null, 
/**
 * 作者。
 */
author?: string | null, };
