// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ChapterItem } from './ChapterItem';

/**
 * 目录阶段模型。
 */
export type TocModel = {
  /**
   * 章节列表。
   */
  chapters: Array<ChapterItem>;
};
