// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../../frb_generated.dart';
import 'lifecycle.dart';
import 'network.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'package:freezed_annotation/freezed_annotation.dart' hide protected;
import 'pipeline.dart';
part 'crawler_rule.freezed.dart';
part 'crawler_rule.g.dart';

/// 多源聚合配置
@freezed
sealed class AggregationConfig with _$AggregationConfig {
  const factory AggregationConfig({
    required bool enabled,
    required int weight,
    required MatchingConfig matching,
  }) = _AggregationConfig;

  factory AggregationConfig.fromJson(Map<String, dynamic> json) =>
      _$AggregationConfigFromJson(json);
}

/// 爬虫规则根结构 - 单一数据源 (Single Source of Truth)
/// 此结构将被自动生成 Dart (freezed) 和 TypeScript 接口
@freezed
sealed class CrawlerRule with _$CrawlerRule {
  const factory CrawlerRule({
    required String id,
    required String name,
    required String description,
    required String author,
    required String version,
    NetworkConfig? network,
    AggregationConfig? aggregation,
    required Lifecycle lifecycle,
  }) = _CrawlerRule;

  factory CrawlerRule.fromJson(Map<String, dynamic> json) =>
      _$CrawlerRuleFromJson(json);
}

/// 匹配配置 - 用于多源结果去重
@freezed
sealed class MatchingConfig with _$MatchingConfig {
  const factory MatchingConfig({
    required String strategy,
    required List<MatchingDimension> dimensions,
  }) = _MatchingConfig;

  factory MatchingConfig.fromJson(Map<String, dynamic> json) =>
      _$MatchingConfigFromJson(json);
}

/// 匹配维度定义
@freezed
sealed class MatchingDimension with _$MatchingDimension {
  const factory MatchingDimension({
    required String field,
    required String matchType,
    required double threshold,
  }) = _MatchingDimension;

  factory MatchingDimension.fromJson(Map<String, dynamic> json) =>
      _$MatchingDimensionFromJson(json);
}
