// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'package:freezed_annotation/freezed_annotation.dart' hide protected;
import 'pipeline.dart';
part 'lifecycle.freezed.dart';
part 'lifecycle.g.dart';

/// 内容页配置
@freezed
sealed class ContentConfig with _$ContentConfig {
  const factory ContentConfig({
    required PipelineGraph pipeline,
    required bool sniffMedia,
  }) = _ContentConfig;

  factory ContentConfig.fromJson(Map<String, dynamic> json) =>
      _$ContentConfigFromJson(json);
}

/// 详情页配置
@freezed
sealed class DetailConfig with _$DetailConfig {
  const factory DetailConfig({
    required PipelineGraph pipeline,
  }) = _DetailConfig;

  factory DetailConfig.fromJson(Map<String, dynamic> json) =>
      _$DetailConfigFromJson(json);
}

/// 发现页配置
@freezed
sealed class ExploreConfig with _$ExploreConfig {
  const factory ExploreConfig({
    required String url,
    required PipelineGraph pipeline,
  }) = _ExploreConfig;

  factory ExploreConfig.fromJson(Map<String, dynamic> json) =>
      _$ExploreConfigFromJson(json);
}

/// 生命周期配置 - 定义爬虫的各个阶段
@freezed
sealed class Lifecycle with _$Lifecycle {
  const factory Lifecycle({
    ExploreConfig? explore,
    SearchConfig? search,
    DetailConfig? detail,
    TocConfig? toc,
    ContentConfig? content,
  }) = _Lifecycle;

  factory Lifecycle.fromJson(Map<String, dynamic> json) =>
      _$LifecycleFromJson(json);
}

/// 搜索页配置
@freezed
sealed class SearchConfig with _$SearchConfig {
  const factory SearchConfig({
    required String url,
    required PipelineGraph pipeline,
  }) = _SearchConfig;

  factory SearchConfig.fromJson(Map<String, dynamic> json) =>
      _$SearchConfigFromJson(json);
}

/// 目录页配置
@freezed
sealed class TocConfig with _$TocConfig {
  const factory TocConfig({
    required PipelineGraph pipeline,
  }) = _TocConfig;

  factory TocConfig.fromJson(Map<String, dynamic> json) =>
      _$TocConfigFromJson(json);
}
