// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'package:freezed_annotation/freezed_annotation.dart' hide protected;
part 'network.freezed.dart';
part 'network.g.dart';

/// 浏览器设备模拟类型
///
/// 提供常用浏览器的 TLS/HTTP2 指纹伪装，内部映射到 wreq 的具体实现
enum Emulation {
  chrome131,
  chrome132,
  chrome133,
  chrome134,
  chrome135,
  chrome136,
  chrome120,
  chrome124,
  chrome126,
  chrome127,
  chrome128,
  chrome129,
  chrome130,
  safari18,
  safari182,
  safari183,
  safari185,
  safari26,
  safariIos1811,
  firefox133,
  firefox135,
  firefox136,
  firefox139,
  firefox142,
  firefox143,
  firefox144,
  firefox145,
  firefox146,
  firefox147,
  edge127,
  edge131,
  edge134,
  edge135,
  edge136,
  edge137,
  edge138,
  edge139,
  edge140,
  edge141,
  edge142,
  edge143,
  edge144,
  edge145,
  okHttp314,
  okHttp412,
  okHttp5,
}

/// 浏览器模拟高级选项
@freezed
sealed class EmulationOption with _$EmulationOption {
  const factory EmulationOption({
    Emulation? emulation,
    EmulationOS? emulationOs,
    bool? skipHttp2,
    bool? skipHeaders,
  }) = _EmulationOption;

  factory EmulationOption.fromJson(Map<String, dynamic> json) =>
      _$EmulationOptionFromJson(json);
}

/// 操作系统模拟类型
enum EmulationOS {
  windows,
  macOs,
  linux,
  android,
  ios,
}

/// 反爬回退配置
@freezed
sealed class FallbackConfig with _$FallbackConfig {
  const factory FallbackConfig({
    required Int32List triggerStatus,
    required List<String> triggerKeywords,
    required String action,
  }) = _FallbackConfig;

  factory FallbackConfig.fromJson(Map<String, dynamic> json) =>
      _$FallbackConfigFromJson(json);
}

/// 网络配置 - 用户友好的规则级配置
/// 具体的 TLS/HTTP2 指纹伪装由内部 wreq 引擎自动处理
@freezed
sealed class NetworkConfig with _$NetworkConfig {
  const factory NetworkConfig({
    required String strategy,
    EmulationOption? emulation,
    BigInt? connectTimeout,
    BigInt? readTimeout,
    Map<String, String>? headers,
    RuleProxyConfig? proxy,
    FallbackConfig? fallback,
  }) = _NetworkConfig;

  factory NetworkConfig.fromJson(Map<String, dynamic> json) =>
      _$NetworkConfigFromJson(json);
}

/// 规则级代理配置 (简化版，用户友好)
@freezed
sealed class RuleProxyConfig with _$RuleProxyConfig {
  const factory RuleProxyConfig({
    required bool enabled,
    String? http,
    String? https,
    String? socks5,
  }) = _RuleProxyConfig;

  factory RuleProxyConfig.fromJson(Map<String, dynamic> json) =>
      _$RuleProxyConfigFromJson(json);
}
