// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'package:freezed_annotation/freezed_annotation.dart' hide protected;
part 'pipeline.freezed.dart';
part 'pipeline.g.dart';

@freezed
sealed class AggregationDef with _$AggregationDef {
  const AggregationDef._();

  const factory AggregationDef.first() = AggregationDef_First;
  const factory AggregationDef.last() = AggregationDef_Last;
  const factory AggregationDef.join({
    required String separator,
  }) = AggregationDef_Join;
  const factory AggregationDef.array() = AggregationDef_Array;

  factory AggregationDef.fromJson(Map<String, dynamic> json) =>
      _$AggregationDefFromJson(json);
}

@freezed
sealed class FlowEdge with _$FlowEdge {
  const factory FlowEdge({
    required String id,
    required String source,
    required String target,
  }) = _FlowEdge;

  factory FlowEdge.fromJson(Map<String, dynamic> json) =>
      _$FlowEdgeFromJson(json);
}

@freezed
sealed class FlowNode with _$FlowNode {
  const factory FlowNode({
    required String id,
    required double x,
    required double y,
    required NodePayload data,
  }) = _FlowNode;

  factory FlowNode.fromJson(Map<String, dynamic> json) =>
      _$FlowNodeFromJson(json);
}

@freezed
sealed class NodePayload with _$NodePayload {
  const NodePayload._();

  const factory NodePayload.selector(
    SelectorDef field0,
  ) = NodePayload_Selector;
  const factory NodePayload.transform(
    TransformDef field0,
  ) = NodePayload_Transform;
  const factory NodePayload.aggregation(
    AggregationDef field0,
  ) = NodePayload_Aggregation;

  factory NodePayload.fromJson(Map<String, dynamic> json) =>
      _$NodePayloadFromJson(json);
}

/// Pipeline 执行请求
///
/// 包含执行 Pipeline 所需的所有输入数据
@freezed
sealed class PipelineExecuteRequest with _$PipelineExecuteRequest {
  const factory PipelineExecuteRequest({
    required String content,
    String? baseUrl,
    String? vars,
    required List<PipelineOperation> operations,
  }) = _PipelineExecuteRequest;

  factory PipelineExecuteRequest.fromJson(Map<String, dynamic> json) =>
      _$PipelineExecuteRequestFromJson(json);
}

/// Pipeline 执行结果
@freezed
sealed class PipelineExecuteResult with _$PipelineExecuteResult {
  const factory PipelineExecuteResult({
    required bool success,
    required List<String> data,
    String? error,
  }) = _PipelineExecuteResult;

  factory PipelineExecuteResult.fromJson(Map<String, dynamic> json) =>
      _$PipelineExecuteResultFromJson(json);
}

@freezed
sealed class PipelineGraph with _$PipelineGraph {
  const factory PipelineGraph({
    required List<FlowNode> nodes,
    required List<FlowEdge> edges,
  }) = _PipelineGraph;

  factory PipelineGraph.fromJson(Map<String, dynamic> json) =>
      _$PipelineGraphFromJson(json);
}

/// Pipeline 操作定义 (简化格式，用于 FFI 传输)
@freezed
sealed class PipelineOperation with _$PipelineOperation {
  const factory PipelineOperation({
    required String opType,
    String? param,
    String? param2,
  }) = _PipelineOperation;

  factory PipelineOperation.fromJson(Map<String, dynamic> json) =>
      _$PipelineOperationFromJson(json);
}

@freezed
sealed class SelectorDef with _$SelectorDef {
  const SelectorDef._();

  const factory SelectorDef.css({
    required String selector,
  }) = SelectorDef_Css;
  const factory SelectorDef.xPath({
    required String query,
  }) = SelectorDef_XPath;
  const factory SelectorDef.jsonPath({
    required String path,
  }) = SelectorDef_JsonPath;
  const factory SelectorDef.regex({
    required String pattern,
  }) = SelectorDef_Regex;

  factory SelectorDef.fromJson(Map<String, dynamic> json) =>
      _$SelectorDefFromJson(json);
}

@freezed
sealed class TransformDef with _$TransformDef {
  const TransformDef._();

  const factory TransformDef.trim() = TransformDef_Trim;
  const factory TransformDef.lower() = TransformDef_Lower;
  const factory TransformDef.upper() = TransformDef_Upper;
  const factory TransformDef.regexReplace({
    required String pattern,
    required String replace,
  }) = TransformDef_RegexReplace;
  const factory TransformDef.text() = TransformDef_Text;
  const factory TransformDef.attr({
    required String name,
  }) = TransformDef_Attr;
  const factory TransformDef.url() = TransformDef_Url;
  const factory TransformDef.js({
    required String script,
  }) = TransformDef_Js;

  factory TransformDef.fromJson(Map<String, dynamic> json) =>
      _$TransformDefFromJson(json);
}
