// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'package:freezed_annotation/freezed_annotation.dart' hide protected;
part 'error.freezed.dart';

@freezed
sealed class BuildError with _$BuildError {
  const BuildError._();

  /// 执行器配置无效
  const factory BuildError.invalidConfig(
    String field0,
  ) = BuildError_InvalidConfig;

  /// 缺少必要参数
  const factory BuildError.missingParameter(
    String field0,
  ) = BuildError_MissingParameter;

  /// 不支持的操作类型
  const factory BuildError.unsupportedOperation(
    String field0,
  ) = BuildError_UnsupportedOperation;

  /// 初始化失败
  const factory BuildError.initializationFailed(
    String field0,
  ) = BuildError_InitializationFailed;
}

@freezed
sealed class CrawlerError with _$CrawlerError {
  const CrawlerError._();

  /// 解析错误 - HTML/XML/JSON 解析失败
  const factory CrawlerError.parseError(
    ParseError field0,
  ) = CrawlerError_ParseError;

  /// 构建错误 - 执行器或配置构建失败
  const factory CrawlerError.buildError(
    BuildError field0,
  ) = CrawlerError_BuildError;

  /// JavaScript 执行错误
  const factory CrawlerError.jsError(
    String field0,
  ) = CrawlerError_JsError;

  /// 输入数据无效
  const factory CrawlerError.invalidInput(
    String field0,
  ) = CrawlerError_InvalidInput;

  /// 选择器未匹配到结果
  const factory CrawlerError.noMatch(
    String field0,
  ) = CrawlerError_NoMatch;

  /// 需要认证（通常为 WAF 拦截）
  const factory CrawlerError.authRequired(
    String field0,
  ) = CrawlerError_AuthRequired;

  /// 阶段配置缺失
  const factory CrawlerError.missingPhaseConfig({
    required String phase,
  }) = CrawlerError_MissingPhaseConfig;

  /// URL 模板替换失败
  const factory CrawlerError.urlTemplateError({
    required String reason,
  }) = CrawlerError_UrlTemplateError;

  /// 不支持的响应类型
  const factory CrawlerError.unsupportedContentType({
    required String contentType,
  }) = CrawlerError_UnsupportedContentType;

  /// 数据解析失败
  const factory CrawlerError.dataParseError({
    required String reason,
  }) = CrawlerError_DataParseError;

  /// 缺少必需的上下文参数
  const factory CrawlerError.missingRequiredContext({
    required String field,
  }) = CrawlerError_MissingRequiredContext;
}

@freezed
sealed class ParseError with _$ParseError {
  const ParseError._();

  /// HTML 解析失败
  const factory ParseError.htmlParse(
    String field0,
  ) = ParseError_HtmlParse;

  /// XML 解析失败
  const factory ParseError.xmlParse(
    String field0,
  ) = ParseError_XmlParse;

  /// JSON 解析失败
  const factory ParseError.jsonParse(
    String field0,
  ) = ParseError_JsonParse;

  /// XPath 语法错误
  const factory ParseError.xPathSyntax(
    String field0,
  ) = ParseError_XPathSyntax;

  /// CSS 选择器语法错误
  const factory ParseError.cssSyntax(
    String field0,
  ) = ParseError_CssSyntax;

  /// JSONPath 语法错误
  const factory ParseError.jsonPathSyntax(
    String field0,
  ) = ParseError_JsonPathSyntax;

  /// 正则表达式语法错误
  const factory ParseError.regexSyntax(
    String field0,
  ) = ParseError_RegexSyntax;
}
