// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `build_engine_context`, `default_run_id`, `engine_error_code`, `engine_error_diagnostics`, `error`, `from_error`, `from_rules_diagnostic`, `invalid`, `map_engine_error`, `new`, `parse_rule`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `assert_receiver_is_total_eq`, `assert_receiver_is_total_eq`, `assert_receiver_is_total_eq`, `assert_receiver_is_total_eq`, `assert_receiver_is_total_eq`, `clone`, `clone`, `clone`, `clone`, `clone`, `eq`, `eq`, `eq`, `eq`, `eq`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`

/// 提供最小 FRB 连通性探针。
bool ping() => RustLib.instance.api.crateFfiPing();

/// 对规则 JSON 做结构校验。
FfiValidationResult validateRule({required String envelopeJson}) =>
    RustLib.instance.api.crateFfiValidateRule(envelopeJson: envelopeJson);

/// 执行规则并返回运行 ID 与可选结果 JSON。
Future<FfiExecuteResponse> executeRule({
  required String envelopeJson,
  FfiExecuteContext? context,
}) => RustLib.instance.api.crateFfiExecuteRule(
  envelopeJson: envelopeJson,
  context: context,
);

/// Flutter 可消费的结构化诊断。
class FfiDiagnostic {
  /// 稳定错误码。
  final String code;

  /// 诊断路径。
  final String path;

  /// 人类可读信息。
  final String message;

  /// 可选节点 ID。
  final String? nodeId;

  const FfiDiagnostic({
    required this.code,
    required this.path,
    required this.message,
    this.nodeId,
  });

  @override
  int get hashCode =>
      code.hashCode ^ path.hashCode ^ message.hashCode ^ nodeId.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is FfiDiagnostic &&
          runtimeType == other.runtimeType &&
          code == other.code &&
          path == other.path &&
          message == other.message &&
          nodeId == other.nodeId;
}

/// 最小执行上下文。
class FfiExecuteContext {
  /// 可选运行 ID。
  final String? runId;

  /// 可选 trace ID。
  final String? traceId;

  /// 可选边通道容量。
  final int? channelCapacity;

  /// 规则标识，用于 rule 级缓存隔离。
  final String? ruleId;

  /// 规则级缓存快照（JSON）。
  final String? ruleKvJson;

  /// 规则级 CookieJar 快照（JSON）。
  final String? cookieJarJson;

  const FfiExecuteContext({
    this.runId,
    this.traceId,
    this.channelCapacity,
    this.ruleId,
    this.ruleKvJson,
    this.cookieJarJson,
  });

  static Future<FfiExecuteContext> default_() =>
      RustLib.instance.api.crateFfiFfiExecuteContextDefault();

  @override
  int get hashCode =>
      runId.hashCode ^
      traceId.hashCode ^
      channelCapacity.hashCode ^
      ruleId.hashCode ^
      ruleKvJson.hashCode ^
      cookieJarJson.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is FfiExecuteContext &&
          runtimeType == other.runtimeType &&
          runId == other.runId &&
          traceId == other.traceId &&
          channelCapacity == other.channelCapacity &&
          ruleId == other.ruleId &&
          ruleKvJson == other.ruleKvJson &&
          cookieJarJson == other.cookieJarJson;
}

/// 结构化执行错误。
class FfiExecuteError {
  /// 稳定错误码。
  final String code;

  /// 人类可读信息。
  final String message;

  /// 结构化诊断。
  final List<FfiDiagnostic> diagnostics;

  const FfiExecuteError({
    required this.code,
    required this.message,
    required this.diagnostics,
  });

  @override
  int get hashCode => code.hashCode ^ message.hashCode ^ diagnostics.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is FfiExecuteError &&
          runtimeType == other.runtimeType &&
          code == other.code &&
          message == other.message &&
          diagnostics == other.diagnostics;
}

/// 执行响应。
class FfiExecuteResponse {
  /// 运行 ID；解析失败时也会尽量返回。
  final String? runId;

  /// 最终结果的 JSON 文本；若无结果或不可序列化则为 `None`。
  final String? initialResultJson;

  /// 结构化错误。
  final FfiExecuteError? error;

  /// 规则级缓存快照（JSON）。
  final String? ruleKvJson;

  /// 规则级 CookieJar 快照（JSON）。
  final String? cookieJarJson;

  const FfiExecuteResponse({
    this.runId,
    this.initialResultJson,
    this.error,
    this.ruleKvJson,
    this.cookieJarJson,
  });

  @override
  int get hashCode =>
      runId.hashCode ^
      initialResultJson.hashCode ^
      error.hashCode ^
      ruleKvJson.hashCode ^
      cookieJarJson.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is FfiExecuteResponse &&
          runtimeType == other.runtimeType &&
          runId == other.runId &&
          initialResultJson == other.initialResultJson &&
          error == other.error &&
          ruleKvJson == other.ruleKvJson &&
          cookieJarJson == other.cookieJarJson;
}

/// 校验结果。
class FfiValidationResult {
  /// 当前规则是否通过校验。
  final bool valid;

  /// 结构化诊断列表。
  final List<FfiDiagnostic> diagnostics;

  const FfiValidationResult({
    required this.valid,
    required this.diagnostics,
  });

  @override
  int get hashCode => valid.hashCode ^ diagnostics.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is FfiValidationResult &&
          runtimeType == other.runtimeType &&
          valid == other.valid &&
          diagnostics == other.diagnostics;
}
