// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

import 'dart:async';
import 'dart:convert';
import 'dart:ffi' as ffi;
import 'ffi.dart';
import 'frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated_io.dart';
import 'rules_ir/normalized_model.dart';

abstract class RustLibApiImplPlatform extends BaseApiImpl<RustLibWire> {
  RustLibApiImplPlatform({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  @protected
  Map<String, String> dco_decode_Map_String_String_None(dynamic raw);

  @protected
  String dco_decode_String(dynamic raw);

  @protected
  bool dco_decode_bool(dynamic raw);

  @protected
  ContentModel dco_decode_box_autoadd_content_model(dynamic raw);

  @protected
  DetailModel dco_decode_box_autoadd_detail_model(dynamic raw);

  @protected
  FfiExecuteContext dco_decode_box_autoadd_ffi_execute_context(dynamic raw);

  @protected
  FfiExecuteError dco_decode_box_autoadd_ffi_execute_error(dynamic raw);

  @protected
  int dco_decode_box_autoadd_i_32(dynamic raw);

  @protected
  MediaExtension dco_decode_box_autoadd_media_extension(dynamic raw);

  @protected
  MediaSpec dco_decode_box_autoadd_media_spec(dynamic raw);

  @protected
  SearchModel dco_decode_box_autoadd_search_model(dynamic raw);

  @protected
  TocModel dco_decode_box_autoadd_toc_model(dynamic raw);

  @protected
  ChapterItem dco_decode_chapter_item(dynamic raw);

  @protected
  ContentModel dco_decode_content_model(dynamic raw);

  @protected
  DetailModel dco_decode_detail_model(dynamic raw);

  @protected
  FfiDiagnostic dco_decode_ffi_diagnostic(dynamic raw);

  @protected
  FfiExecuteContext dco_decode_ffi_execute_context(dynamic raw);

  @protected
  FfiExecuteError dco_decode_ffi_execute_error(dynamic raw);

  @protected
  FfiExecuteResponse dco_decode_ffi_execute_response(dynamic raw);

  @protected
  FfiValidationResult dco_decode_ffi_validation_result(dynamic raw);

  @protected
  int dco_decode_i_32(dynamic raw);

  @protected
  List<String> dco_decode_list_String(dynamic raw);

  @protected
  List<ChapterItem> dco_decode_list_chapter_item(dynamic raw);

  @protected
  List<FfiDiagnostic> dco_decode_list_ffi_diagnostic(dynamic raw);

  @protected
  List<MediaAsset> dco_decode_list_media_asset(dynamic raw);

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw);

  @protected
  List<(String, String)> dco_decode_list_record_string_string(dynamic raw);

  @protected
  List<SearchItem> dco_decode_list_search_item(dynamic raw);

  @protected
  MediaAsset dco_decode_media_asset(dynamic raw);

  @protected
  MediaExtension dco_decode_media_extension(dynamic raw);

  @protected
  MediaSpec dco_decode_media_spec(dynamic raw);

  @protected
  MediaType dco_decode_media_type(dynamic raw);

  @protected
  NormalizedModel dco_decode_normalized_model(dynamic raw);

  @protected
  String? dco_decode_opt_String(dynamic raw);

  @protected
  ContentModel? dco_decode_opt_box_autoadd_content_model(dynamic raw);

  @protected
  DetailModel? dco_decode_opt_box_autoadd_detail_model(dynamic raw);

  @protected
  FfiExecuteContext? dco_decode_opt_box_autoadd_ffi_execute_context(
    dynamic raw,
  );

  @protected
  FfiExecuteError? dco_decode_opt_box_autoadd_ffi_execute_error(dynamic raw);

  @protected
  int? dco_decode_opt_box_autoadd_i_32(dynamic raw);

  @protected
  MediaExtension? dco_decode_opt_box_autoadd_media_extension(dynamic raw);

  @protected
  MediaSpec? dco_decode_opt_box_autoadd_media_spec(dynamic raw);

  @protected
  SearchModel? dco_decode_opt_box_autoadd_search_model(dynamic raw);

  @protected
  TocModel? dco_decode_opt_box_autoadd_toc_model(dynamic raw);

  @protected
  (String, String) dco_decode_record_string_string(dynamic raw);

  @protected
  SearchItem dco_decode_search_item(dynamic raw);

  @protected
  SearchModel dco_decode_search_model(dynamic raw);

  @protected
  TocModel dco_decode_toc_model(dynamic raw);

  @protected
  int dco_decode_u_8(dynamic raw);

  @protected
  void dco_decode_unit(dynamic raw);

  @protected
  Map<String, String> sse_decode_Map_String_String_None(
    SseDeserializer deserializer,
  );

  @protected
  String sse_decode_String(SseDeserializer deserializer);

  @protected
  bool sse_decode_bool(SseDeserializer deserializer);

  @protected
  ContentModel sse_decode_box_autoadd_content_model(
    SseDeserializer deserializer,
  );

  @protected
  DetailModel sse_decode_box_autoadd_detail_model(SseDeserializer deserializer);

  @protected
  FfiExecuteContext sse_decode_box_autoadd_ffi_execute_context(
    SseDeserializer deserializer,
  );

  @protected
  FfiExecuteError sse_decode_box_autoadd_ffi_execute_error(
    SseDeserializer deserializer,
  );

  @protected
  int sse_decode_box_autoadd_i_32(SseDeserializer deserializer);

  @protected
  MediaExtension sse_decode_box_autoadd_media_extension(
    SseDeserializer deserializer,
  );

  @protected
  MediaSpec sse_decode_box_autoadd_media_spec(SseDeserializer deserializer);

  @protected
  SearchModel sse_decode_box_autoadd_search_model(SseDeserializer deserializer);

  @protected
  TocModel sse_decode_box_autoadd_toc_model(SseDeserializer deserializer);

  @protected
  ChapterItem sse_decode_chapter_item(SseDeserializer deserializer);

  @protected
  ContentModel sse_decode_content_model(SseDeserializer deserializer);

  @protected
  DetailModel sse_decode_detail_model(SseDeserializer deserializer);

  @protected
  FfiDiagnostic sse_decode_ffi_diagnostic(SseDeserializer deserializer);

  @protected
  FfiExecuteContext sse_decode_ffi_execute_context(
    SseDeserializer deserializer,
  );

  @protected
  FfiExecuteError sse_decode_ffi_execute_error(SseDeserializer deserializer);

  @protected
  FfiExecuteResponse sse_decode_ffi_execute_response(
    SseDeserializer deserializer,
  );

  @protected
  FfiValidationResult sse_decode_ffi_validation_result(
    SseDeserializer deserializer,
  );

  @protected
  int sse_decode_i_32(SseDeserializer deserializer);

  @protected
  List<String> sse_decode_list_String(SseDeserializer deserializer);

  @protected
  List<ChapterItem> sse_decode_list_chapter_item(SseDeserializer deserializer);

  @protected
  List<FfiDiagnostic> sse_decode_list_ffi_diagnostic(
    SseDeserializer deserializer,
  );

  @protected
  List<MediaAsset> sse_decode_list_media_asset(SseDeserializer deserializer);

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer);

  @protected
  List<(String, String)> sse_decode_list_record_string_string(
    SseDeserializer deserializer,
  );

  @protected
  List<SearchItem> sse_decode_list_search_item(SseDeserializer deserializer);

  @protected
  MediaAsset sse_decode_media_asset(SseDeserializer deserializer);

  @protected
  MediaExtension sse_decode_media_extension(SseDeserializer deserializer);

  @protected
  MediaSpec sse_decode_media_spec(SseDeserializer deserializer);

  @protected
  MediaType sse_decode_media_type(SseDeserializer deserializer);

  @protected
  NormalizedModel sse_decode_normalized_model(SseDeserializer deserializer);

  @protected
  String? sse_decode_opt_String(SseDeserializer deserializer);

  @protected
  ContentModel? sse_decode_opt_box_autoadd_content_model(
    SseDeserializer deserializer,
  );

  @protected
  DetailModel? sse_decode_opt_box_autoadd_detail_model(
    SseDeserializer deserializer,
  );

  @protected
  FfiExecuteContext? sse_decode_opt_box_autoadd_ffi_execute_context(
    SseDeserializer deserializer,
  );

  @protected
  FfiExecuteError? sse_decode_opt_box_autoadd_ffi_execute_error(
    SseDeserializer deserializer,
  );

  @protected
  int? sse_decode_opt_box_autoadd_i_32(SseDeserializer deserializer);

  @protected
  MediaExtension? sse_decode_opt_box_autoadd_media_extension(
    SseDeserializer deserializer,
  );

  @protected
  MediaSpec? sse_decode_opt_box_autoadd_media_spec(
    SseDeserializer deserializer,
  );

  @protected
  SearchModel? sse_decode_opt_box_autoadd_search_model(
    SseDeserializer deserializer,
  );

  @protected
  TocModel? sse_decode_opt_box_autoadd_toc_model(SseDeserializer deserializer);

  @protected
  (String, String) sse_decode_record_string_string(
    SseDeserializer deserializer,
  );

  @protected
  SearchItem sse_decode_search_item(SseDeserializer deserializer);

  @protected
  SearchModel sse_decode_search_model(SseDeserializer deserializer);

  @protected
  TocModel sse_decode_toc_model(SseDeserializer deserializer);

  @protected
  int sse_decode_u_8(SseDeserializer deserializer);

  @protected
  void sse_decode_unit(SseDeserializer deserializer);

  @protected
  void sse_encode_Map_String_String_None(
    Map<String, String> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_String(String self, SseSerializer serializer);

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_content_model(
    ContentModel self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_detail_model(
    DetailModel self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_ffi_execute_context(
    FfiExecuteContext self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_ffi_execute_error(
    FfiExecuteError self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_i_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_media_extension(
    MediaExtension self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_media_spec(
    MediaSpec self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_search_model(
    SearchModel self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_toc_model(
    TocModel self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_chapter_item(ChapterItem self, SseSerializer serializer);

  @protected
  void sse_encode_content_model(ContentModel self, SseSerializer serializer);

  @protected
  void sse_encode_detail_model(DetailModel self, SseSerializer serializer);

  @protected
  void sse_encode_ffi_diagnostic(FfiDiagnostic self, SseSerializer serializer);

  @protected
  void sse_encode_ffi_execute_context(
    FfiExecuteContext self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_ffi_execute_error(
    FfiExecuteError self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_ffi_execute_response(
    FfiExecuteResponse self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_ffi_validation_result(
    FfiValidationResult self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_list_String(List<String> self, SseSerializer serializer);

  @protected
  void sse_encode_list_chapter_item(
    List<ChapterItem> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_ffi_diagnostic(
    List<FfiDiagnostic> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_media_asset(
    List<MediaAsset> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_prim_u_8_strict(
    Uint8List self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_record_string_string(
    List<(String, String)> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_search_item(
    List<SearchItem> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_media_asset(MediaAsset self, SseSerializer serializer);

  @protected
  void sse_encode_media_extension(
    MediaExtension self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_media_spec(MediaSpec self, SseSerializer serializer);

  @protected
  void sse_encode_media_type(MediaType self, SseSerializer serializer);

  @protected
  void sse_encode_normalized_model(
    NormalizedModel self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_String(String? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_content_model(
    ContentModel? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_box_autoadd_detail_model(
    DetailModel? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_box_autoadd_ffi_execute_context(
    FfiExecuteContext? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_box_autoadd_ffi_execute_error(
    FfiExecuteError? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_box_autoadd_i_32(int? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_media_extension(
    MediaExtension? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_box_autoadd_media_spec(
    MediaSpec? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_box_autoadd_search_model(
    SearchModel? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_box_autoadd_toc_model(
    TocModel? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_record_string_string(
    (String, String) self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_search_item(SearchItem self, SseSerializer serializer);

  @protected
  void sse_encode_search_model(SearchModel self, SseSerializer serializer);

  @protected
  void sse_encode_toc_model(TocModel self, SseSerializer serializer);

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer);

  @protected
  void sse_encode_unit(void self, SseSerializer serializer);
}

// Section: wire_class

class RustLibWire implements BaseWire {
  factory RustLibWire.fromExternalLibrary(ExternalLibrary lib) =>
      RustLibWire(lib.ffiDynamicLibrary);

  /// Holds the symbol lookup function.
  final ffi.Pointer<T> Function<T extends ffi.NativeType>(String symbolName)
  _lookup;

  /// The symbols are looked up in [dynamicLibrary].
  RustLibWire(ffi.DynamicLibrary dynamicLibrary)
    : _lookup = dynamicLibrary.lookup;
}
