// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

// Static analysis wrongly picks the IO variant, thus ignore this
// ignore_for_file: argument_type_not_assignable

import 'api/crawler_models.dart';
import 'api/lifecycle_executor.dart';
import 'dart:async';
import 'dart:convert';
import 'domain/phase.dart';
import 'domain/rule/crawler_rule.dart';
import 'domain/rule/lifecycle.dart';
import 'domain/rule/network.dart';
import 'domain/rule/pipeline.dart';
import 'error.dart';
import 'frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated_web.dart';

abstract class RustLibApiImplPlatform extends BaseApiImpl<RustLibWire> {
  RustLibApiImplPlatform({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  @protected
  Map<String, String> dco_decode_Map_String_String_None(dynamic raw);

  @protected
  String dco_decode_String(dynamic raw);

  @protected
  AggregationConfig dco_decode_aggregation_config(dynamic raw);

  @protected
  AggregationDef dco_decode_aggregation_def(dynamic raw);

  @protected
  bool dco_decode_bool(dynamic raw);

  @protected
  AggregationConfig dco_decode_box_autoadd_aggregation_config(dynamic raw);

  @protected
  AggregationDef dco_decode_box_autoadd_aggregation_def(dynamic raw);

  @protected
  bool dco_decode_box_autoadd_bool(dynamic raw);

  @protected
  BuildError dco_decode_box_autoadd_build_error(dynamic raw);

  @protected
  ContentConfig dco_decode_box_autoadd_content_config(dynamic raw);

  @protected
  ContentData dco_decode_box_autoadd_content_data(dynamic raw);

  @protected
  CrawlerError dco_decode_box_autoadd_crawler_error(dynamic raw);

  @protected
  CrawlerRule dco_decode_box_autoadd_crawler_rule(dynamic raw);

  @protected
  DetailConfig dco_decode_box_autoadd_detail_config(dynamic raw);

  @protected
  DetailData dco_decode_box_autoadd_detail_data(dynamic raw);

  @protected
  Emulation dco_decode_box_autoadd_emulation(dynamic raw);

  @protected
  EmulationOption dco_decode_box_autoadd_emulation_option(dynamic raw);

  @protected
  EmulationOS dco_decode_box_autoadd_emulation_os(dynamic raw);

  @protected
  ExploreConfig dco_decode_box_autoadd_explore_config(dynamic raw);

  @protected
  ExploreData dco_decode_box_autoadd_explore_data(dynamic raw);

  @protected
  FallbackConfig dco_decode_box_autoadd_fallback_config(dynamic raw);

  @protected
  NetworkConfig dco_decode_box_autoadd_network_config(dynamic raw);

  @protected
  ParseError dco_decode_box_autoadd_parse_error(dynamic raw);

  @protected
  PhaseContext dco_decode_box_autoadd_phase_context(dynamic raw);

  @protected
  PhaseData dco_decode_box_autoadd_phase_data(dynamic raw);

  @protected
  RuleProxyConfig dco_decode_box_autoadd_rule_proxy_config(dynamic raw);

  @protected
  SearchConfig dco_decode_box_autoadd_search_config(dynamic raw);

  @protected
  SearchData dco_decode_box_autoadd_search_data(dynamic raw);

  @protected
  SelectorDef dco_decode_box_autoadd_selector_def(dynamic raw);

  @protected
  TocConfig dco_decode_box_autoadd_toc_config(dynamic raw);

  @protected
  TocData dco_decode_box_autoadd_toc_data(dynamic raw);

  @protected
  TransformDef dco_decode_box_autoadd_transform_def(dynamic raw);

  @protected
  int dco_decode_box_autoadd_u_32(dynamic raw);

  @protected
  BigInt dco_decode_box_autoadd_u_64(dynamic raw);

  @protected
  BuildError dco_decode_build_error(dynamic raw);

  @protected
  ChapterItem dco_decode_chapter_item(dynamic raw);

  @protected
  ContentConfig dco_decode_content_config(dynamic raw);

  @protected
  ContentData dco_decode_content_data(dynamic raw);

  @protected
  ContentType dco_decode_content_type(dynamic raw);

  @protected
  CrawlerError dco_decode_crawler_error(dynamic raw);

  @protected
  CrawlerRule dco_decode_crawler_rule(dynamic raw);

  @protected
  DetailConfig dco_decode_detail_config(dynamic raw);

  @protected
  DetailData dco_decode_detail_data(dynamic raw);

  @protected
  Emulation dco_decode_emulation(dynamic raw);

  @protected
  EmulationOption dco_decode_emulation_option(dynamic raw);

  @protected
  EmulationOS dco_decode_emulation_os(dynamic raw);

  @protected
  ExploreConfig dco_decode_explore_config(dynamic raw);

  @protected
  ExploreData dco_decode_explore_data(dynamic raw);

  @protected
  double dco_decode_f_64(dynamic raw);

  @protected
  FallbackConfig dco_decode_fallback_config(dynamic raw);

  @protected
  FlowEdge dco_decode_flow_edge(dynamic raw);

  @protected
  FlowNode dco_decode_flow_node(dynamic raw);

  @protected
  int dco_decode_i_32(dynamic raw);

  @protected
  Lifecycle dco_decode_lifecycle(dynamic raw);

  @protected
  LifecyclePhase dco_decode_lifecycle_phase(dynamic raw);

  @protected
  List<String> dco_decode_list_String(dynamic raw);

  @protected
  List<ChapterItem> dco_decode_list_chapter_item(dynamic raw);

  @protected
  List<FlowEdge> dco_decode_list_flow_edge(dynamic raw);

  @protected
  List<FlowNode> dco_decode_list_flow_node(dynamic raw);

  @protected
  List<MatchingDimension> dco_decode_list_matching_dimension(dynamic raw);

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw);

  @protected
  List<(String, String)> dco_decode_list_record_string_string(dynamic raw);

  @protected
  List<SearchItem> dco_decode_list_search_item(dynamic raw);

  @protected
  MatchingConfig dco_decode_matching_config(dynamic raw);

  @protected
  MatchingDimension dco_decode_matching_dimension(dynamic raw);

  @protected
  NetworkConfig dco_decode_network_config(dynamic raw);

  @protected
  NodePayload dco_decode_node_payload(dynamic raw);

  @protected
  Map<String, String>? dco_decode_opt_Map_String_String_None(dynamic raw);

  @protected
  String? dco_decode_opt_String(dynamic raw);

  @protected
  AggregationConfig? dco_decode_opt_box_autoadd_aggregation_config(dynamic raw);

  @protected
  bool? dco_decode_opt_box_autoadd_bool(dynamic raw);

  @protected
  ContentConfig? dco_decode_opt_box_autoadd_content_config(dynamic raw);

  @protected
  CrawlerError? dco_decode_opt_box_autoadd_crawler_error(dynamic raw);

  @protected
  DetailConfig? dco_decode_opt_box_autoadd_detail_config(dynamic raw);

  @protected
  Emulation? dco_decode_opt_box_autoadd_emulation(dynamic raw);

  @protected
  EmulationOption? dco_decode_opt_box_autoadd_emulation_option(dynamic raw);

  @protected
  EmulationOS? dco_decode_opt_box_autoadd_emulation_os(dynamic raw);

  @protected
  ExploreConfig? dco_decode_opt_box_autoadd_explore_config(dynamic raw);

  @protected
  FallbackConfig? dco_decode_opt_box_autoadd_fallback_config(dynamic raw);

  @protected
  NetworkConfig? dco_decode_opt_box_autoadd_network_config(dynamic raw);

  @protected
  PhaseData? dco_decode_opt_box_autoadd_phase_data(dynamic raw);

  @protected
  RuleProxyConfig? dco_decode_opt_box_autoadd_rule_proxy_config(dynamic raw);

  @protected
  SearchConfig? dco_decode_opt_box_autoadd_search_config(dynamic raw);

  @protected
  TocConfig? dco_decode_opt_box_autoadd_toc_config(dynamic raw);

  @protected
  int? dco_decode_opt_box_autoadd_u_32(dynamic raw);

  @protected
  BigInt? dco_decode_opt_box_autoadd_u_64(dynamic raw);

  @protected
  ParseError dco_decode_parse_error(dynamic raw);

  @protected
  PhaseContext dco_decode_phase_context(dynamic raw);

  @protected
  PhaseData dco_decode_phase_data(dynamic raw);

  @protected
  PhaseResult dco_decode_phase_result(dynamic raw);

  @protected
  PipelineGraph dco_decode_pipeline_graph(dynamic raw);

  @protected
  (String, String) dco_decode_record_string_string(dynamic raw);

  @protected
  RuleProxyConfig dco_decode_rule_proxy_config(dynamic raw);

  @protected
  SearchConfig dco_decode_search_config(dynamic raw);

  @protected
  SearchData dco_decode_search_data(dynamic raw);

  @protected
  SearchItem dco_decode_search_item(dynamic raw);

  @protected
  SelectorDef dco_decode_selector_def(dynamic raw);

  @protected
  TocConfig dco_decode_toc_config(dynamic raw);

  @protected
  TocData dco_decode_toc_data(dynamic raw);

  @protected
  TransformDef dco_decode_transform_def(dynamic raw);

  @protected
  int dco_decode_u_32(dynamic raw);

  @protected
  BigInt dco_decode_u_64(dynamic raw);

  @protected
  int dco_decode_u_8(dynamic raw);

  @protected
  void dco_decode_unit(dynamic raw);

  @protected
  Map<String, String> sse_decode_Map_String_String_None(
    SseDeserializer deserializer,
  );

  @protected
  String sse_decode_String(SseDeserializer deserializer);

  @protected
  AggregationConfig sse_decode_aggregation_config(SseDeserializer deserializer);

  @protected
  AggregationDef sse_decode_aggregation_def(SseDeserializer deserializer);

  @protected
  bool sse_decode_bool(SseDeserializer deserializer);

  @protected
  AggregationConfig sse_decode_box_autoadd_aggregation_config(
    SseDeserializer deserializer,
  );

  @protected
  AggregationDef sse_decode_box_autoadd_aggregation_def(
    SseDeserializer deserializer,
  );

  @protected
  bool sse_decode_box_autoadd_bool(SseDeserializer deserializer);

  @protected
  BuildError sse_decode_box_autoadd_build_error(SseDeserializer deserializer);

  @protected
  ContentConfig sse_decode_box_autoadd_content_config(
    SseDeserializer deserializer,
  );

  @protected
  ContentData sse_decode_box_autoadd_content_data(SseDeserializer deserializer);

  @protected
  CrawlerError sse_decode_box_autoadd_crawler_error(
    SseDeserializer deserializer,
  );

  @protected
  CrawlerRule sse_decode_box_autoadd_crawler_rule(SseDeserializer deserializer);

  @protected
  DetailConfig sse_decode_box_autoadd_detail_config(
    SseDeserializer deserializer,
  );

  @protected
  DetailData sse_decode_box_autoadd_detail_data(SseDeserializer deserializer);

  @protected
  Emulation sse_decode_box_autoadd_emulation(SseDeserializer deserializer);

  @protected
  EmulationOption sse_decode_box_autoadd_emulation_option(
    SseDeserializer deserializer,
  );

  @protected
  EmulationOS sse_decode_box_autoadd_emulation_os(SseDeserializer deserializer);

  @protected
  ExploreConfig sse_decode_box_autoadd_explore_config(
    SseDeserializer deserializer,
  );

  @protected
  ExploreData sse_decode_box_autoadd_explore_data(SseDeserializer deserializer);

  @protected
  FallbackConfig sse_decode_box_autoadd_fallback_config(
    SseDeserializer deserializer,
  );

  @protected
  NetworkConfig sse_decode_box_autoadd_network_config(
    SseDeserializer deserializer,
  );

  @protected
  ParseError sse_decode_box_autoadd_parse_error(SseDeserializer deserializer);

  @protected
  PhaseContext sse_decode_box_autoadd_phase_context(
    SseDeserializer deserializer,
  );

  @protected
  PhaseData sse_decode_box_autoadd_phase_data(SseDeserializer deserializer);

  @protected
  RuleProxyConfig sse_decode_box_autoadd_rule_proxy_config(
    SseDeserializer deserializer,
  );

  @protected
  SearchConfig sse_decode_box_autoadd_search_config(
    SseDeserializer deserializer,
  );

  @protected
  SearchData sse_decode_box_autoadd_search_data(SseDeserializer deserializer);

  @protected
  SelectorDef sse_decode_box_autoadd_selector_def(SseDeserializer deserializer);

  @protected
  TocConfig sse_decode_box_autoadd_toc_config(SseDeserializer deserializer);

  @protected
  TocData sse_decode_box_autoadd_toc_data(SseDeserializer deserializer);

  @protected
  TransformDef sse_decode_box_autoadd_transform_def(
    SseDeserializer deserializer,
  );

  @protected
  int sse_decode_box_autoadd_u_32(SseDeserializer deserializer);

  @protected
  BigInt sse_decode_box_autoadd_u_64(SseDeserializer deserializer);

  @protected
  BuildError sse_decode_build_error(SseDeserializer deserializer);

  @protected
  ChapterItem sse_decode_chapter_item(SseDeserializer deserializer);

  @protected
  ContentConfig sse_decode_content_config(SseDeserializer deserializer);

  @protected
  ContentData sse_decode_content_data(SseDeserializer deserializer);

  @protected
  ContentType sse_decode_content_type(SseDeserializer deserializer);

  @protected
  CrawlerError sse_decode_crawler_error(SseDeserializer deserializer);

  @protected
  CrawlerRule sse_decode_crawler_rule(SseDeserializer deserializer);

  @protected
  DetailConfig sse_decode_detail_config(SseDeserializer deserializer);

  @protected
  DetailData sse_decode_detail_data(SseDeserializer deserializer);

  @protected
  Emulation sse_decode_emulation(SseDeserializer deserializer);

  @protected
  EmulationOption sse_decode_emulation_option(SseDeserializer deserializer);

  @protected
  EmulationOS sse_decode_emulation_os(SseDeserializer deserializer);

  @protected
  ExploreConfig sse_decode_explore_config(SseDeserializer deserializer);

  @protected
  ExploreData sse_decode_explore_data(SseDeserializer deserializer);

  @protected
  double sse_decode_f_64(SseDeserializer deserializer);

  @protected
  FallbackConfig sse_decode_fallback_config(SseDeserializer deserializer);

  @protected
  FlowEdge sse_decode_flow_edge(SseDeserializer deserializer);

  @protected
  FlowNode sse_decode_flow_node(SseDeserializer deserializer);

  @protected
  int sse_decode_i_32(SseDeserializer deserializer);

  @protected
  Lifecycle sse_decode_lifecycle(SseDeserializer deserializer);

  @protected
  LifecyclePhase sse_decode_lifecycle_phase(SseDeserializer deserializer);

  @protected
  List<String> sse_decode_list_String(SseDeserializer deserializer);

  @protected
  List<ChapterItem> sse_decode_list_chapter_item(SseDeserializer deserializer);

  @protected
  List<FlowEdge> sse_decode_list_flow_edge(SseDeserializer deserializer);

  @protected
  List<FlowNode> sse_decode_list_flow_node(SseDeserializer deserializer);

  @protected
  List<MatchingDimension> sse_decode_list_matching_dimension(
    SseDeserializer deserializer,
  );

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer);

  @protected
  List<(String, String)> sse_decode_list_record_string_string(
    SseDeserializer deserializer,
  );

  @protected
  List<SearchItem> sse_decode_list_search_item(SseDeserializer deserializer);

  @protected
  MatchingConfig sse_decode_matching_config(SseDeserializer deserializer);

  @protected
  MatchingDimension sse_decode_matching_dimension(SseDeserializer deserializer);

  @protected
  NetworkConfig sse_decode_network_config(SseDeserializer deserializer);

  @protected
  NodePayload sse_decode_node_payload(SseDeserializer deserializer);

  @protected
  Map<String, String>? sse_decode_opt_Map_String_String_None(
    SseDeserializer deserializer,
  );

  @protected
  String? sse_decode_opt_String(SseDeserializer deserializer);

  @protected
  AggregationConfig? sse_decode_opt_box_autoadd_aggregation_config(
    SseDeserializer deserializer,
  );

  @protected
  bool? sse_decode_opt_box_autoadd_bool(SseDeserializer deserializer);

  @protected
  ContentConfig? sse_decode_opt_box_autoadd_content_config(
    SseDeserializer deserializer,
  );

  @protected
  CrawlerError? sse_decode_opt_box_autoadd_crawler_error(
    SseDeserializer deserializer,
  );

  @protected
  DetailConfig? sse_decode_opt_box_autoadd_detail_config(
    SseDeserializer deserializer,
  );

  @protected
  Emulation? sse_decode_opt_box_autoadd_emulation(SseDeserializer deserializer);

  @protected
  EmulationOption? sse_decode_opt_box_autoadd_emulation_option(
    SseDeserializer deserializer,
  );

  @protected
  EmulationOS? sse_decode_opt_box_autoadd_emulation_os(
    SseDeserializer deserializer,
  );

  @protected
  ExploreConfig? sse_decode_opt_box_autoadd_explore_config(
    SseDeserializer deserializer,
  );

  @protected
  FallbackConfig? sse_decode_opt_box_autoadd_fallback_config(
    SseDeserializer deserializer,
  );

  @protected
  NetworkConfig? sse_decode_opt_box_autoadd_network_config(
    SseDeserializer deserializer,
  );

  @protected
  PhaseData? sse_decode_opt_box_autoadd_phase_data(
    SseDeserializer deserializer,
  );

  @protected
  RuleProxyConfig? sse_decode_opt_box_autoadd_rule_proxy_config(
    SseDeserializer deserializer,
  );

  @protected
  SearchConfig? sse_decode_opt_box_autoadd_search_config(
    SseDeserializer deserializer,
  );

  @protected
  TocConfig? sse_decode_opt_box_autoadd_toc_config(
    SseDeserializer deserializer,
  );

  @protected
  int? sse_decode_opt_box_autoadd_u_32(SseDeserializer deserializer);

  @protected
  BigInt? sse_decode_opt_box_autoadd_u_64(SseDeserializer deserializer);

  @protected
  ParseError sse_decode_parse_error(SseDeserializer deserializer);

  @protected
  PhaseContext sse_decode_phase_context(SseDeserializer deserializer);

  @protected
  PhaseData sse_decode_phase_data(SseDeserializer deserializer);

  @protected
  PhaseResult sse_decode_phase_result(SseDeserializer deserializer);

  @protected
  PipelineGraph sse_decode_pipeline_graph(SseDeserializer deserializer);

  @protected
  (String, String) sse_decode_record_string_string(
    SseDeserializer deserializer,
  );

  @protected
  RuleProxyConfig sse_decode_rule_proxy_config(SseDeserializer deserializer);

  @protected
  SearchConfig sse_decode_search_config(SseDeserializer deserializer);

  @protected
  SearchData sse_decode_search_data(SseDeserializer deserializer);

  @protected
  SearchItem sse_decode_search_item(SseDeserializer deserializer);

  @protected
  SelectorDef sse_decode_selector_def(SseDeserializer deserializer);

  @protected
  TocConfig sse_decode_toc_config(SseDeserializer deserializer);

  @protected
  TocData sse_decode_toc_data(SseDeserializer deserializer);

  @protected
  TransformDef sse_decode_transform_def(SseDeserializer deserializer);

  @protected
  int sse_decode_u_32(SseDeserializer deserializer);

  @protected
  BigInt sse_decode_u_64(SseDeserializer deserializer);

  @protected
  int sse_decode_u_8(SseDeserializer deserializer);

  @protected
  void sse_decode_unit(SseDeserializer deserializer);

  @protected
  void sse_encode_Map_String_String_None(
    Map<String, String> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_String(String self, SseSerializer serializer);

  @protected
  void sse_encode_aggregation_config(
    AggregationConfig self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_aggregation_def(
    AggregationDef self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_aggregation_config(
    AggregationConfig self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_aggregation_def(
    AggregationDef self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_bool(bool self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_build_error(
    BuildError self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_content_config(
    ContentConfig self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_content_data(
    ContentData self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_crawler_error(
    CrawlerError self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_crawler_rule(
    CrawlerRule self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_detail_config(
    DetailConfig self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_detail_data(
    DetailData self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_emulation(
    Emulation self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_emulation_option(
    EmulationOption self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_emulation_os(
    EmulationOS self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_explore_config(
    ExploreConfig self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_explore_data(
    ExploreData self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_fallback_config(
    FallbackConfig self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_network_config(
    NetworkConfig self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_parse_error(
    ParseError self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_phase_context(
    PhaseContext self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_phase_data(
    PhaseData self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_rule_proxy_config(
    RuleProxyConfig self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_search_config(
    SearchConfig self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_search_data(
    SearchData self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_selector_def(
    SelectorDef self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_toc_config(
    TocConfig self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_toc_data(TocData self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_transform_def(
    TransformDef self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_u_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_u_64(BigInt self, SseSerializer serializer);

  @protected
  void sse_encode_build_error(BuildError self, SseSerializer serializer);

  @protected
  void sse_encode_chapter_item(ChapterItem self, SseSerializer serializer);

  @protected
  void sse_encode_content_config(ContentConfig self, SseSerializer serializer);

  @protected
  void sse_encode_content_data(ContentData self, SseSerializer serializer);

  @protected
  void sse_encode_content_type(ContentType self, SseSerializer serializer);

  @protected
  void sse_encode_crawler_error(CrawlerError self, SseSerializer serializer);

  @protected
  void sse_encode_crawler_rule(CrawlerRule self, SseSerializer serializer);

  @protected
  void sse_encode_detail_config(DetailConfig self, SseSerializer serializer);

  @protected
  void sse_encode_detail_data(DetailData self, SseSerializer serializer);

  @protected
  void sse_encode_emulation(Emulation self, SseSerializer serializer);

  @protected
  void sse_encode_emulation_option(
    EmulationOption self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_emulation_os(EmulationOS self, SseSerializer serializer);

  @protected
  void sse_encode_explore_config(ExploreConfig self, SseSerializer serializer);

  @protected
  void sse_encode_explore_data(ExploreData self, SseSerializer serializer);

  @protected
  void sse_encode_f_64(double self, SseSerializer serializer);

  @protected
  void sse_encode_fallback_config(
    FallbackConfig self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_flow_edge(FlowEdge self, SseSerializer serializer);

  @protected
  void sse_encode_flow_node(FlowNode self, SseSerializer serializer);

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_lifecycle(Lifecycle self, SseSerializer serializer);

  @protected
  void sse_encode_lifecycle_phase(
    LifecyclePhase self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_String(List<String> self, SseSerializer serializer);

  @protected
  void sse_encode_list_chapter_item(
    List<ChapterItem> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_flow_edge(List<FlowEdge> self, SseSerializer serializer);

  @protected
  void sse_encode_list_flow_node(List<FlowNode> self, SseSerializer serializer);

  @protected
  void sse_encode_list_matching_dimension(
    List<MatchingDimension> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_prim_u_8_strict(
    Uint8List self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_record_string_string(
    List<(String, String)> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_search_item(
    List<SearchItem> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_matching_config(
    MatchingConfig self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_matching_dimension(
    MatchingDimension self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_network_config(NetworkConfig self, SseSerializer serializer);

  @protected
  void sse_encode_node_payload(NodePayload self, SseSerializer serializer);

  @protected
  void sse_encode_opt_Map_String_String_None(
    Map<String, String>? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_String(String? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_aggregation_config(
    AggregationConfig? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_box_autoadd_bool(bool? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_content_config(
    ContentConfig? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_box_autoadd_crawler_error(
    CrawlerError? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_box_autoadd_detail_config(
    DetailConfig? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_box_autoadd_emulation(
    Emulation? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_box_autoadd_emulation_option(
    EmulationOption? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_box_autoadd_emulation_os(
    EmulationOS? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_box_autoadd_explore_config(
    ExploreConfig? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_box_autoadd_fallback_config(
    FallbackConfig? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_box_autoadd_network_config(
    NetworkConfig? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_box_autoadd_phase_data(
    PhaseData? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_box_autoadd_rule_proxy_config(
    RuleProxyConfig? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_box_autoadd_search_config(
    SearchConfig? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_box_autoadd_toc_config(
    TocConfig? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_box_autoadd_u_32(int? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_u_64(BigInt? self, SseSerializer serializer);

  @protected
  void sse_encode_parse_error(ParseError self, SseSerializer serializer);

  @protected
  void sse_encode_phase_context(PhaseContext self, SseSerializer serializer);

  @protected
  void sse_encode_phase_data(PhaseData self, SseSerializer serializer);

  @protected
  void sse_encode_phase_result(PhaseResult self, SseSerializer serializer);

  @protected
  void sse_encode_pipeline_graph(PipelineGraph self, SseSerializer serializer);

  @protected
  void sse_encode_record_string_string(
    (String, String) self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_rule_proxy_config(
    RuleProxyConfig self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_search_config(SearchConfig self, SseSerializer serializer);

  @protected
  void sse_encode_search_data(SearchData self, SseSerializer serializer);

  @protected
  void sse_encode_search_item(SearchItem self, SseSerializer serializer);

  @protected
  void sse_encode_selector_def(SelectorDef self, SseSerializer serializer);

  @protected
  void sse_encode_toc_config(TocConfig self, SseSerializer serializer);

  @protected
  void sse_encode_toc_data(TocData self, SseSerializer serializer);

  @protected
  void sse_encode_transform_def(TransformDef self, SseSerializer serializer);

  @protected
  void sse_encode_u_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_u_64(BigInt self, SseSerializer serializer);

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer);

  @protected
  void sse_encode_unit(void self, SseSerializer serializer);
}

// Section: wire_class

class RustLibWire implements BaseWire {
  RustLibWire.fromExternalLibrary(ExternalLibrary lib);
}

@JS('wasm_bindgen')
external RustLibWasmModule get wasmModule;

@JS()
@anonymous
extension type RustLibWasmModule._(JSObject _) implements JSObject {}
