// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

import 'dart:async';
import 'dart:convert';
import 'ffi.dart';
import 'frb_generated.dart';
import 'frb_generated.io.dart'
    if (dart.library.js_interop) 'frb_generated.web.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'rules_ir/normalized_model.dart';

/// Main entrypoint of the Rust API
class RustLib extends BaseEntrypoint<RustLibApi, RustLibApiImpl, RustLibWire> {
  @internal
  static final instance = RustLib._();

  RustLib._();

  /// Initialize flutter_rust_bridge
  static Future<void> init({
    RustLibApi? api,
    BaseHandler? handler,
    ExternalLibrary? externalLibrary,
    bool forceSameCodegenVersion = true,
  }) async {
    await instance.initImpl(
      api: api,
      handler: handler,
      externalLibrary: externalLibrary,
      forceSameCodegenVersion: forceSameCodegenVersion,
    );
  }

  /// Initialize flutter_rust_bridge in mock mode.
  /// No libraries for FFI are loaded.
  static void initMock({
    required RustLibApi api,
  }) {
    instance.initMockImpl(
      api: api,
    );
  }

  /// Dispose flutter_rust_bridge
  ///
  /// The call to this function is optional, since flutter_rust_bridge (and everything else)
  /// is automatically disposed when the app stops.
  static void dispose() => instance.disposeImpl();

  @override
  ApiImplConstructor<RustLibApiImpl, RustLibWire> get apiImplConstructor =>
      RustLibApiImpl.new;

  @override
  WireConstructor<RustLibWire> get wireConstructor =>
      RustLibWire.fromExternalLibrary;

  @override
  Future<void> executeRustInitializers() async {}

  @override
  ExternalLibraryLoaderConfig get defaultExternalLibraryLoaderConfig =>
      kDefaultExternalLibraryLoaderConfig;

  @override
  String get codegenVersion => '2.11.1';

  @override
  int get rustContentHash => -550374770;

  static const kDefaultExternalLibraryLoaderConfig =
      ExternalLibraryLoaderConfig(
        stem: 'spectra_native',
        ioDirectory: 'rust/target/release/',
        webPrefix: 'pkg/',
      );
}

abstract class RustLibApi extends BaseApi {
  Future<FfiExecuteResponse> crateFfiExecuteRule({
    required String envelopeJson,
    FfiExecuteContext? context,
  });

  Future<FfiExecuteContext> crateFfiFfiExecuteContextDefault();

  bool crateFfiPing();

  FfiValidationResult crateFfiValidateRule({required String envelopeJson});
}

class RustLibApiImpl extends RustLibApiImplPlatform implements RustLibApi {
  RustLibApiImpl({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  @override
  Future<FfiExecuteResponse> crateFfiExecuteRule({
    required String envelopeJson,
    FfiExecuteContext? context,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(envelopeJson, serializer);
          sse_encode_opt_box_autoadd_ffi_execute_context(context, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 1,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_ffi_execute_response,
          decodeErrorData: null,
        ),
        constMeta: kCrateFfiExecuteRuleConstMeta,
        argValues: [envelopeJson, context],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateFfiExecuteRuleConstMeta => const TaskConstMeta(
    debugName: "execute_rule",
    argNames: ["envelopeJson", "context"],
  );

  @override
  Future<FfiExecuteContext> crateFfiFfiExecuteContextDefault() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 2,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_ffi_execute_context,
          decodeErrorData: null,
        ),
        constMeta: kCrateFfiFfiExecuteContextDefaultConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateFfiFfiExecuteContextDefaultConstMeta =>
      const TaskConstMeta(
        debugName: "ffi_execute_context_default",
        argNames: [],
      );

  @override
  bool crateFfiPing() {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 3)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_bool,
          decodeErrorData: null,
        ),
        constMeta: kCrateFfiPingConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateFfiPingConstMeta => const TaskConstMeta(
    debugName: "ping",
    argNames: [],
  );

  @override
  FfiValidationResult crateFfiValidateRule({required String envelopeJson}) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(envelopeJson, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 4)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_ffi_validation_result,
          decodeErrorData: null,
        ),
        constMeta: kCrateFfiValidateRuleConstMeta,
        argValues: [envelopeJson],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateFfiValidateRuleConstMeta => const TaskConstMeta(
    debugName: "validate_rule",
    argNames: ["envelopeJson"],
  );

  @protected
  Map<String, String> dco_decode_Map_String_String_None(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return Map.fromEntries(
      dco_decode_list_record_string_string(
        raw,
      ).map((e) => MapEntry(e.$1, e.$2)),
    );
  }

  @protected
  String dco_decode_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as String;
  }

  @protected
  bool dco_decode_bool(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as bool;
  }

  @protected
  ContentModel dco_decode_box_autoadd_content_model(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_content_model(raw);
  }

  @protected
  DetailModel dco_decode_box_autoadd_detail_model(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_detail_model(raw);
  }

  @protected
  FfiExecuteContext dco_decode_box_autoadd_ffi_execute_context(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_ffi_execute_context(raw);
  }

  @protected
  FfiExecuteError dco_decode_box_autoadd_ffi_execute_error(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_ffi_execute_error(raw);
  }

  @protected
  int dco_decode_box_autoadd_i_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  MediaExtension dco_decode_box_autoadd_media_extension(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_media_extension(raw);
  }

  @protected
  MediaSpec dco_decode_box_autoadd_media_spec(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_media_spec(raw);
  }

  @protected
  SearchModel dco_decode_box_autoadd_search_model(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_search_model(raw);
  }

  @protected
  TocModel dco_decode_box_autoadd_toc_model(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_toc_model(raw);
  }

  @protected
  ChapterItem dco_decode_chapter_item(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 2)
      throw Exception('unexpected arr length: expect 2 but see ${arr.length}');
    return ChapterItem(
      title: dco_decode_String(arr[0]),
      url: dco_decode_opt_String(arr[1]),
    );
  }

  @protected
  ContentModel dco_decode_content_model(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 3)
      throw Exception('unexpected arr length: expect 3 but see ${arr.length}');
    return ContentModel(
      contentTextHtml: dco_decode_opt_String(arr[0]),
      contentTextPlain: dco_decode_opt_String(arr[1]),
      mediaAssets: dco_decode_list_media_asset(arr[2]),
    );
  }

  @protected
  DetailModel dco_decode_detail_model(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 5)
      throw Exception('unexpected arr length: expect 5 but see ${arr.length}');
    return DetailModel(
      title: dco_decode_String(arr[0]),
      cover: dco_decode_opt_String(arr[1]),
      author: dco_decode_opt_String(arr[2]),
      description: dco_decode_opt_String(arr[3]),
      tags: dco_decode_list_String(arr[4]),
    );
  }

  @protected
  FfiDiagnostic dco_decode_ffi_diagnostic(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 4)
      throw Exception('unexpected arr length: expect 4 but see ${arr.length}');
    return FfiDiagnostic(
      code: dco_decode_String(arr[0]),
      path: dco_decode_String(arr[1]),
      message: dco_decode_String(arr[2]),
      nodeId: dco_decode_opt_String(arr[3]),
    );
  }

  @protected
  FfiExecuteContext dco_decode_ffi_execute_context(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 3)
      throw Exception('unexpected arr length: expect 3 but see ${arr.length}');
    return FfiExecuteContext(
      runId: dco_decode_opt_String(arr[0]),
      traceId: dco_decode_opt_String(arr[1]),
      channelCapacity: dco_decode_opt_box_autoadd_i_32(arr[2]),
    );
  }

  @protected
  FfiExecuteError dco_decode_ffi_execute_error(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 3)
      throw Exception('unexpected arr length: expect 3 but see ${arr.length}');
    return FfiExecuteError(
      code: dco_decode_String(arr[0]),
      message: dco_decode_String(arr[1]),
      diagnostics: dco_decode_list_ffi_diagnostic(arr[2]),
    );
  }

  @protected
  FfiExecuteResponse dco_decode_ffi_execute_response(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 3)
      throw Exception('unexpected arr length: expect 3 but see ${arr.length}');
    return FfiExecuteResponse(
      runId: dco_decode_opt_String(arr[0]),
      initialResultJson: dco_decode_opt_String(arr[1]),
      error: dco_decode_opt_box_autoadd_ffi_execute_error(arr[2]),
    );
  }

  @protected
  FfiValidationResult dco_decode_ffi_validation_result(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 2)
      throw Exception('unexpected arr length: expect 2 but see ${arr.length}');
    return FfiValidationResult(
      valid: dco_decode_bool(arr[0]),
      diagnostics: dco_decode_list_ffi_diagnostic(arr[1]),
    );
  }

  @protected
  int dco_decode_i_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  List<String> dco_decode_list_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_String).toList();
  }

  @protected
  List<ChapterItem> dco_decode_list_chapter_item(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_chapter_item).toList();
  }

  @protected
  List<FfiDiagnostic> dco_decode_list_ffi_diagnostic(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_ffi_diagnostic).toList();
  }

  @protected
  List<MediaAsset> dco_decode_list_media_asset(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_media_asset).toList();
  }

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as Uint8List;
  }

  @protected
  List<(String, String)> dco_decode_list_record_string_string(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_record_string_string).toList();
  }

  @protected
  List<SearchItem> dco_decode_list_search_item(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_search_item).toList();
  }

  @protected
  MediaAsset dco_decode_media_asset(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 4)
      throw Exception('unexpected arr length: expect 4 but see ${arr.length}');
    return MediaAsset(
      mediaType: dco_decode_media_type(arr[0]),
      url: dco_decode_String(arr[1]),
      title: dco_decode_opt_String(arr[2]),
      cover: dco_decode_opt_String(arr[3]),
    );
  }

  @protected
  MediaExtension dco_decode_media_extension(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 5)
      throw Exception('unexpected arr length: expect 5 but see ${arr.length}');
    return MediaExtension(
      video: dco_decode_opt_box_autoadd_media_spec(arr[0]),
      music: dco_decode_opt_box_autoadd_media_spec(arr[1]),
      novel: dco_decode_opt_box_autoadd_media_spec(arr[2]),
      comic: dco_decode_opt_box_autoadd_media_spec(arr[3]),
      image: dco_decode_opt_box_autoadd_media_spec(arr[4]),
    );
  }

  @protected
  MediaSpec dco_decode_media_spec(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 1)
      throw Exception('unexpected arr length: expect 1 but see ${arr.length}');
    return MediaSpec(
      extra: dco_decode_Map_String_String_None(arr[0]),
    );
  }

  @protected
  MediaType dco_decode_media_type(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return MediaType.values[raw as int];
  }

  @protected
  NormalizedModel dco_decode_normalized_model(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 5)
      throw Exception('unexpected arr length: expect 5 but see ${arr.length}');
    return NormalizedModel(
      search: dco_decode_opt_box_autoadd_search_model(arr[0]),
      detail: dco_decode_opt_box_autoadd_detail_model(arr[1]),
      toc: dco_decode_opt_box_autoadd_toc_model(arr[2]),
      content: dco_decode_opt_box_autoadd_content_model(arr[3]),
      media: dco_decode_opt_box_autoadd_media_extension(arr[4]),
    );
  }

  @protected
  String? dco_decode_opt_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_String(raw);
  }

  @protected
  ContentModel? dco_decode_opt_box_autoadd_content_model(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_box_autoadd_content_model(raw);
  }

  @protected
  DetailModel? dco_decode_opt_box_autoadd_detail_model(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_box_autoadd_detail_model(raw);
  }

  @protected
  FfiExecuteContext? dco_decode_opt_box_autoadd_ffi_execute_context(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_box_autoadd_ffi_execute_context(raw);
  }

  @protected
  FfiExecuteError? dco_decode_opt_box_autoadd_ffi_execute_error(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_box_autoadd_ffi_execute_error(raw);
  }

  @protected
  int? dco_decode_opt_box_autoadd_i_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_box_autoadd_i_32(raw);
  }

  @protected
  MediaExtension? dco_decode_opt_box_autoadd_media_extension(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_box_autoadd_media_extension(raw);
  }

  @protected
  MediaSpec? dco_decode_opt_box_autoadd_media_spec(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_box_autoadd_media_spec(raw);
  }

  @protected
  SearchModel? dco_decode_opt_box_autoadd_search_model(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_box_autoadd_search_model(raw);
  }

  @protected
  TocModel? dco_decode_opt_box_autoadd_toc_model(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_box_autoadd_toc_model(raw);
  }

  @protected
  (String, String) dco_decode_record_string_string(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 2) {
      throw Exception('Expected 2 elements, got ${arr.length}');
    }
    return (
      dco_decode_String(arr[0]),
      dco_decode_String(arr[1]),
    );
  }

  @protected
  SearchItem dco_decode_search_item(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 4)
      throw Exception('unexpected arr length: expect 4 but see ${arr.length}');
    return SearchItem(
      title: dco_decode_String(arr[0]),
      url: dco_decode_String(arr[1]),
      cover: dco_decode_opt_String(arr[2]),
      author: dco_decode_opt_String(arr[3]),
    );
  }

  @protected
  SearchModel dco_decode_search_model(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 1)
      throw Exception('unexpected arr length: expect 1 but see ${arr.length}');
    return SearchModel(
      items: dco_decode_list_search_item(arr[0]),
    );
  }

  @protected
  TocModel dco_decode_toc_model(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 1)
      throw Exception('unexpected arr length: expect 1 but see ${arr.length}');
    return TocModel(
      chapters: dco_decode_list_chapter_item(arr[0]),
    );
  }

  @protected
  int dco_decode_u_8(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  void dco_decode_unit(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return;
  }

  @protected
  Map<String, String> sse_decode_Map_String_String_None(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_list_record_string_string(deserializer);
    return Map.fromEntries(inner.map((e) => MapEntry(e.$1, e.$2)));
  }

  @protected
  String sse_decode_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_list_prim_u_8_strict(deserializer);
    return utf8.decoder.convert(inner);
  }

  @protected
  bool sse_decode_bool(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8() != 0;
  }

  @protected
  ContentModel sse_decode_box_autoadd_content_model(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_content_model(deserializer));
  }

  @protected
  DetailModel sse_decode_box_autoadd_detail_model(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_detail_model(deserializer));
  }

  @protected
  FfiExecuteContext sse_decode_box_autoadd_ffi_execute_context(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_ffi_execute_context(deserializer));
  }

  @protected
  FfiExecuteError sse_decode_box_autoadd_ffi_execute_error(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_ffi_execute_error(deserializer));
  }

  @protected
  int sse_decode_box_autoadd_i_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_i_32(deserializer));
  }

  @protected
  MediaExtension sse_decode_box_autoadd_media_extension(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_media_extension(deserializer));
  }

  @protected
  MediaSpec sse_decode_box_autoadd_media_spec(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_media_spec(deserializer));
  }

  @protected
  SearchModel sse_decode_box_autoadd_search_model(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_search_model(deserializer));
  }

  @protected
  TocModel sse_decode_box_autoadd_toc_model(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_toc_model(deserializer));
  }

  @protected
  ChapterItem sse_decode_chapter_item(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_title = sse_decode_String(deserializer);
    var var_url = sse_decode_opt_String(deserializer);
    return ChapterItem(title: var_title, url: var_url);
  }

  @protected
  ContentModel sse_decode_content_model(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_contentTextHtml = sse_decode_opt_String(deserializer);
    var var_contentTextPlain = sse_decode_opt_String(deserializer);
    var var_mediaAssets = sse_decode_list_media_asset(deserializer);
    return ContentModel(
      contentTextHtml: var_contentTextHtml,
      contentTextPlain: var_contentTextPlain,
      mediaAssets: var_mediaAssets,
    );
  }

  @protected
  DetailModel sse_decode_detail_model(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_title = sse_decode_String(deserializer);
    var var_cover = sse_decode_opt_String(deserializer);
    var var_author = sse_decode_opt_String(deserializer);
    var var_description = sse_decode_opt_String(deserializer);
    var var_tags = sse_decode_list_String(deserializer);
    return DetailModel(
      title: var_title,
      cover: var_cover,
      author: var_author,
      description: var_description,
      tags: var_tags,
    );
  }

  @protected
  FfiDiagnostic sse_decode_ffi_diagnostic(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_code = sse_decode_String(deserializer);
    var var_path = sse_decode_String(deserializer);
    var var_message = sse_decode_String(deserializer);
    var var_nodeId = sse_decode_opt_String(deserializer);
    return FfiDiagnostic(
      code: var_code,
      path: var_path,
      message: var_message,
      nodeId: var_nodeId,
    );
  }

  @protected
  FfiExecuteContext sse_decode_ffi_execute_context(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_runId = sse_decode_opt_String(deserializer);
    var var_traceId = sse_decode_opt_String(deserializer);
    var var_channelCapacity = sse_decode_opt_box_autoadd_i_32(deserializer);
    return FfiExecuteContext(
      runId: var_runId,
      traceId: var_traceId,
      channelCapacity: var_channelCapacity,
    );
  }

  @protected
  FfiExecuteError sse_decode_ffi_execute_error(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_code = sse_decode_String(deserializer);
    var var_message = sse_decode_String(deserializer);
    var var_diagnostics = sse_decode_list_ffi_diagnostic(deserializer);
    return FfiExecuteError(
      code: var_code,
      message: var_message,
      diagnostics: var_diagnostics,
    );
  }

  @protected
  FfiExecuteResponse sse_decode_ffi_execute_response(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_runId = sse_decode_opt_String(deserializer);
    var var_initialResultJson = sse_decode_opt_String(deserializer);
    var var_error = sse_decode_opt_box_autoadd_ffi_execute_error(deserializer);
    return FfiExecuteResponse(
      runId: var_runId,
      initialResultJson: var_initialResultJson,
      error: var_error,
    );
  }

  @protected
  FfiValidationResult sse_decode_ffi_validation_result(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_valid = sse_decode_bool(deserializer);
    var var_diagnostics = sse_decode_list_ffi_diagnostic(deserializer);
    return FfiValidationResult(valid: var_valid, diagnostics: var_diagnostics);
  }

  @protected
  int sse_decode_i_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getInt32();
  }

  @protected
  List<String> sse_decode_list_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <String>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_String(deserializer));
    }
    return ans_;
  }

  @protected
  List<ChapterItem> sse_decode_list_chapter_item(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <ChapterItem>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_chapter_item(deserializer));
    }
    return ans_;
  }

  @protected
  List<FfiDiagnostic> sse_decode_list_ffi_diagnostic(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <FfiDiagnostic>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_ffi_diagnostic(deserializer));
    }
    return ans_;
  }

  @protected
  List<MediaAsset> sse_decode_list_media_asset(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <MediaAsset>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_media_asset(deserializer));
    }
    return ans_;
  }

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var len_ = sse_decode_i_32(deserializer);
    return deserializer.buffer.getUint8List(len_);
  }

  @protected
  List<(String, String)> sse_decode_list_record_string_string(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <(String, String)>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_record_string_string(deserializer));
    }
    return ans_;
  }

  @protected
  List<SearchItem> sse_decode_list_search_item(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <SearchItem>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_search_item(deserializer));
    }
    return ans_;
  }

  @protected
  MediaAsset sse_decode_media_asset(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_mediaType = sse_decode_media_type(deserializer);
    var var_url = sse_decode_String(deserializer);
    var var_title = sse_decode_opt_String(deserializer);
    var var_cover = sse_decode_opt_String(deserializer);
    return MediaAsset(
      mediaType: var_mediaType,
      url: var_url,
      title: var_title,
      cover: var_cover,
    );
  }

  @protected
  MediaExtension sse_decode_media_extension(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_video = sse_decode_opt_box_autoadd_media_spec(deserializer);
    var var_music = sse_decode_opt_box_autoadd_media_spec(deserializer);
    var var_novel = sse_decode_opt_box_autoadd_media_spec(deserializer);
    var var_comic = sse_decode_opt_box_autoadd_media_spec(deserializer);
    var var_image = sse_decode_opt_box_autoadd_media_spec(deserializer);
    return MediaExtension(
      video: var_video,
      music: var_music,
      novel: var_novel,
      comic: var_comic,
      image: var_image,
    );
  }

  @protected
  MediaSpec sse_decode_media_spec(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_extra = sse_decode_Map_String_String_None(deserializer);
    return MediaSpec(extra: var_extra);
  }

  @protected
  MediaType sse_decode_media_type(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_i_32(deserializer);
    return MediaType.values[inner];
  }

  @protected
  NormalizedModel sse_decode_normalized_model(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_search = sse_decode_opt_box_autoadd_search_model(deserializer);
    var var_detail = sse_decode_opt_box_autoadd_detail_model(deserializer);
    var var_toc = sse_decode_opt_box_autoadd_toc_model(deserializer);
    var var_content = sse_decode_opt_box_autoadd_content_model(deserializer);
    var var_media = sse_decode_opt_box_autoadd_media_extension(deserializer);
    return NormalizedModel(
      search: var_search,
      detail: var_detail,
      toc: var_toc,
      content: var_content,
      media: var_media,
    );
  }

  @protected
  String? sse_decode_opt_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_String(deserializer));
    } else {
      return null;
    }
  }

  @protected
  ContentModel? sse_decode_opt_box_autoadd_content_model(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_box_autoadd_content_model(deserializer));
    } else {
      return null;
    }
  }

  @protected
  DetailModel? sse_decode_opt_box_autoadd_detail_model(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_box_autoadd_detail_model(deserializer));
    } else {
      return null;
    }
  }

  @protected
  FfiExecuteContext? sse_decode_opt_box_autoadd_ffi_execute_context(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_box_autoadd_ffi_execute_context(deserializer));
    } else {
      return null;
    }
  }

  @protected
  FfiExecuteError? sse_decode_opt_box_autoadd_ffi_execute_error(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_box_autoadd_ffi_execute_error(deserializer));
    } else {
      return null;
    }
  }

  @protected
  int? sse_decode_opt_box_autoadd_i_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_box_autoadd_i_32(deserializer));
    } else {
      return null;
    }
  }

  @protected
  MediaExtension? sse_decode_opt_box_autoadd_media_extension(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_box_autoadd_media_extension(deserializer));
    } else {
      return null;
    }
  }

  @protected
  MediaSpec? sse_decode_opt_box_autoadd_media_spec(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_box_autoadd_media_spec(deserializer));
    } else {
      return null;
    }
  }

  @protected
  SearchModel? sse_decode_opt_box_autoadd_search_model(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_box_autoadd_search_model(deserializer));
    } else {
      return null;
    }
  }

  @protected
  TocModel? sse_decode_opt_box_autoadd_toc_model(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_box_autoadd_toc_model(deserializer));
    } else {
      return null;
    }
  }

  @protected
  (String, String) sse_decode_record_string_string(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_field0 = sse_decode_String(deserializer);
    var var_field1 = sse_decode_String(deserializer);
    return (var_field0, var_field1);
  }

  @protected
  SearchItem sse_decode_search_item(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_title = sse_decode_String(deserializer);
    var var_url = sse_decode_String(deserializer);
    var var_cover = sse_decode_opt_String(deserializer);
    var var_author = sse_decode_opt_String(deserializer);
    return SearchItem(
      title: var_title,
      url: var_url,
      cover: var_cover,
      author: var_author,
    );
  }

  @protected
  SearchModel sse_decode_search_model(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_items = sse_decode_list_search_item(deserializer);
    return SearchModel(items: var_items);
  }

  @protected
  TocModel sse_decode_toc_model(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_chapters = sse_decode_list_chapter_item(deserializer);
    return TocModel(chapters: var_chapters);
  }

  @protected
  int sse_decode_u_8(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8();
  }

  @protected
  void sse_decode_unit(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  void sse_encode_Map_String_String_None(
    Map<String, String> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_list_record_string_string(
      self.entries.map((e) => (e.key, e.value)).toList(),
      serializer,
    );
  }

  @protected
  void sse_encode_String(String self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_list_prim_u_8_strict(utf8.encoder.convert(self), serializer);
  }

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self ? 1 : 0);
  }

  @protected
  void sse_encode_box_autoadd_content_model(
    ContentModel self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_content_model(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_detail_model(
    DetailModel self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_detail_model(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_ffi_execute_context(
    FfiExecuteContext self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_ffi_execute_context(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_ffi_execute_error(
    FfiExecuteError self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_ffi_execute_error(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_i_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_media_extension(
    MediaExtension self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_media_extension(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_media_spec(
    MediaSpec self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_media_spec(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_search_model(
    SearchModel self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_search_model(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_toc_model(
    TocModel self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_toc_model(self, serializer);
  }

  @protected
  void sse_encode_chapter_item(ChapterItem self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.title, serializer);
    sse_encode_opt_String(self.url, serializer);
  }

  @protected
  void sse_encode_content_model(ContentModel self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_opt_String(self.contentTextHtml, serializer);
    sse_encode_opt_String(self.contentTextPlain, serializer);
    sse_encode_list_media_asset(self.mediaAssets, serializer);
  }

  @protected
  void sse_encode_detail_model(DetailModel self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.title, serializer);
    sse_encode_opt_String(self.cover, serializer);
    sse_encode_opt_String(self.author, serializer);
    sse_encode_opt_String(self.description, serializer);
    sse_encode_list_String(self.tags, serializer);
  }

  @protected
  void sse_encode_ffi_diagnostic(FfiDiagnostic self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.code, serializer);
    sse_encode_String(self.path, serializer);
    sse_encode_String(self.message, serializer);
    sse_encode_opt_String(self.nodeId, serializer);
  }

  @protected
  void sse_encode_ffi_execute_context(
    FfiExecuteContext self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_opt_String(self.runId, serializer);
    sse_encode_opt_String(self.traceId, serializer);
    sse_encode_opt_box_autoadd_i_32(self.channelCapacity, serializer);
  }

  @protected
  void sse_encode_ffi_execute_error(
    FfiExecuteError self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.code, serializer);
    sse_encode_String(self.message, serializer);
    sse_encode_list_ffi_diagnostic(self.diagnostics, serializer);
  }

  @protected
  void sse_encode_ffi_execute_response(
    FfiExecuteResponse self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_opt_String(self.runId, serializer);
    sse_encode_opt_String(self.initialResultJson, serializer);
    sse_encode_opt_box_autoadd_ffi_execute_error(self.error, serializer);
  }

  @protected
  void sse_encode_ffi_validation_result(
    FfiValidationResult self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_bool(self.valid, serializer);
    sse_encode_list_ffi_diagnostic(self.diagnostics, serializer);
  }

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putInt32(self);
  }

  @protected
  void sse_encode_list_String(List<String> self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_String(item, serializer);
    }
  }

  @protected
  void sse_encode_list_chapter_item(
    List<ChapterItem> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_chapter_item(item, serializer);
    }
  }

  @protected
  void sse_encode_list_ffi_diagnostic(
    List<FfiDiagnostic> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_ffi_diagnostic(item, serializer);
    }
  }

  @protected
  void sse_encode_list_media_asset(
    List<MediaAsset> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_media_asset(item, serializer);
    }
  }

  @protected
  void sse_encode_list_prim_u_8_strict(
    Uint8List self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    serializer.buffer.putUint8List(self);
  }

  @protected
  void sse_encode_list_record_string_string(
    List<(String, String)> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_record_string_string(item, serializer);
    }
  }

  @protected
  void sse_encode_list_search_item(
    List<SearchItem> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_search_item(item, serializer);
    }
  }

  @protected
  void sse_encode_media_asset(MediaAsset self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_media_type(self.mediaType, serializer);
    sse_encode_String(self.url, serializer);
    sse_encode_opt_String(self.title, serializer);
    sse_encode_opt_String(self.cover, serializer);
  }

  @protected
  void sse_encode_media_extension(
    MediaExtension self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_opt_box_autoadd_media_spec(self.video, serializer);
    sse_encode_opt_box_autoadd_media_spec(self.music, serializer);
    sse_encode_opt_box_autoadd_media_spec(self.novel, serializer);
    sse_encode_opt_box_autoadd_media_spec(self.comic, serializer);
    sse_encode_opt_box_autoadd_media_spec(self.image, serializer);
  }

  @protected
  void sse_encode_media_spec(MediaSpec self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_Map_String_String_None(self.extra, serializer);
  }

  @protected
  void sse_encode_media_type(MediaType self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.index, serializer);
  }

  @protected
  void sse_encode_normalized_model(
    NormalizedModel self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_opt_box_autoadd_search_model(self.search, serializer);
    sse_encode_opt_box_autoadd_detail_model(self.detail, serializer);
    sse_encode_opt_box_autoadd_toc_model(self.toc, serializer);
    sse_encode_opt_box_autoadd_content_model(self.content, serializer);
    sse_encode_opt_box_autoadd_media_extension(self.media, serializer);
  }

  @protected
  void sse_encode_opt_String(String? self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_String(self, serializer);
    }
  }

  @protected
  void sse_encode_opt_box_autoadd_content_model(
    ContentModel? self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_box_autoadd_content_model(self, serializer);
    }
  }

  @protected
  void sse_encode_opt_box_autoadd_detail_model(
    DetailModel? self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_box_autoadd_detail_model(self, serializer);
    }
  }

  @protected
  void sse_encode_opt_box_autoadd_ffi_execute_context(
    FfiExecuteContext? self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_box_autoadd_ffi_execute_context(self, serializer);
    }
  }

  @protected
  void sse_encode_opt_box_autoadd_ffi_execute_error(
    FfiExecuteError? self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_box_autoadd_ffi_execute_error(self, serializer);
    }
  }

  @protected
  void sse_encode_opt_box_autoadd_i_32(int? self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_box_autoadd_i_32(self, serializer);
    }
  }

  @protected
  void sse_encode_opt_box_autoadd_media_extension(
    MediaExtension? self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_box_autoadd_media_extension(self, serializer);
    }
  }

  @protected
  void sse_encode_opt_box_autoadd_media_spec(
    MediaSpec? self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_box_autoadd_media_spec(self, serializer);
    }
  }

  @protected
  void sse_encode_opt_box_autoadd_search_model(
    SearchModel? self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_box_autoadd_search_model(self, serializer);
    }
  }

  @protected
  void sse_encode_opt_box_autoadd_toc_model(
    TocModel? self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_box_autoadd_toc_model(self, serializer);
    }
  }

  @protected
  void sse_encode_record_string_string(
    (String, String) self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.$1, serializer);
    sse_encode_String(self.$2, serializer);
  }

  @protected
  void sse_encode_search_item(SearchItem self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.title, serializer);
    sse_encode_String(self.url, serializer);
    sse_encode_opt_String(self.cover, serializer);
    sse_encode_opt_String(self.author, serializer);
  }

  @protected
  void sse_encode_search_model(SearchModel self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_list_search_item(self.items, serializer);
  }

  @protected
  void sse_encode_toc_model(TocModel self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_list_chapter_item(self.chapters, serializer);
  }

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self);
  }

  @protected
  void sse_encode_unit(void self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }
}
