// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * 图元信息。
 */
export type GraphMetadata = { 
/**
 * 图名称。
 */
name?: string | null, 
/**
 * 图描述。
 */
description?: string | null, 
/**
 * 任意标签。
 */
tags: Array<string>, };
